### ISSUE TITLE
web[][o.e.c.t.TransportClientNodesService] failed to get node info for {#transport#-1}

### ISSUE THREAD

**Issue by osquem** [SonarSource/docker-sonarqube#169]
Hi, I've run the container like this: 
`**docker run -it --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube -Dsonar.ce.javaOpts=-Xmx2048m -Dsonar.web.javaOpts=-Xmx2048m**` 

but it failed to start. The output below ...

Thanks in advance for any help! 

```
2018.04.19 16:31:01 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2018.04.19 16:31:01 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2018.04.19 16:31:02 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonarqube/temp/conf/es
2018.04.19 16:31:02 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2018.04.19 16:31:03 INFO  app[][o.e.p.PluginsService] no modules loaded
2018.04.19 16:31:03 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2018.04.19 16:31:13 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2018.04.19 16:31:13 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonarqube]: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -Xmx2048m -Djava.security.egd=file:/dev/./urandom -cp ./lib/common/*:./lib/server/*:/opt/sonarqube/lib/jdbc/h2/h2-1.3.176.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process8022727295397202279properties
2018.04.19 16:31:14 INFO  web[][o.s.p.ProcessEntryPoint] Starting web
2018.04.19 16:31:15 INFO  web[][o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
2018.04.19 16:31:16 INFO  web[][o.e.p.PluginsService] no modules loaded
2018.04.19 16:31:16 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
2018.04.19 16:31:16 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
2018.04.19 16:31:16 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
2018.04.19 16:31:16 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2018.04.19 16:31:19 INFO  web[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [127.0.0.1:9001]
2018.04.19 16:31:19 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 7.0.0.36138 / 3b827a9a9a4b133c9fbe168aec8db44d78efeaeb
2018.04.19 16:31:19 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Starting embedded database on port 9092 with url jdbc:h2:tcp://127.0.0.1:9092/sonar
2018.04.19 16:31:19 INFO  web[][o.s.s.p.d.EmbeddedDatabase] Embedded database started. Data stored in: /opt/sonarqube/data
2018.04.19 16:31:19 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:h2:tcp://127.0.0.1:9092/sonar
2018.04.19 16:31:19 WARN  web[][o.s.d.DatabaseChecker] H2 database should be used for evaluation purpose only
2018.04.19 16:31:21 INFO  web[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /opt/sonarqube
2018.04.19 16:31:21 INFO  web[][o.s.s.u.SystemPasscodeImpl] System authentication by passcode is disabled
2018.04.19 16:31:21 INFO  web[][o.s.s.p.d.m.h.MigrationHistoryTableImpl] Creating table schema_migrations
2018.04.19 16:31:21 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarPHP [php] installed
2018.04.19 16:31:21 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin Flex [flex] installed
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarJS [javascript] installed
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarQube :: Plugins :: SCM :: Git [scmgit] installed
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarJava [java] installed
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarTS [typescript] installed
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarQube :: Plugins :: SCM :: SVN [scmsvn] installed
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarXML [xml] installed
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarC# [csharp] installed
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarPython [python] installed
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin Flex / 2.3 / 79167f762219bea1fd181ff5ef6ca4b34abd1675
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarC# / 6.7.1.4347 / c8c4474682a3cd67f345ff46b2a7e1c62c85441c
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarJS / 4.0.0.5862 / 7c3166ea3f0526e74aa53e521d2fee2290fa0820
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarJava / 5.1.0.13090 / 5d2c41b3da0a3a6c11417a6d17d011d7a1fe8ba2
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarPHP / 2.12.1.3018 / 75c2cebff53eeee63fe7eafc5e31c188270d5fe8
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarPython / 1.9.0.2010 / f17988b34c750c96c13ef5bdcc0645167233e3ad
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarQube :: Plugins :: SCM :: Git / 1.3.0.869 / 4da53e3f9e55f4f2e5796625cb0c5768ed152079
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarQube :: Plugins :: SCM :: SVN / 1.6.0.860 / 2111fdbd1dddda4ad6d4ed6486fd0b18c1010d3b
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarTS / 1.5.0.2122 / 7eb12e7593b8e02616914773451c6118f230c57a
2018.04.19 16:31:22 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarXML / 1.4.3.1027 / 39588245cecf538bb27be4e496ff303b0143d20b
2018.04.19 16:31:22 INFO  web[][o.s.s.p.d.m.AutoDbMigration] Automatically perform DB migration on fresh install
2018.04.19 16:31:23 INFO  web[][o.s.s.p.Platform] Database has been automatically updated
2018.04.19 16:31:23 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.ws.WebServiceFilter@e58bb3d [pattern=UrlPattern{inclusions=[/api/system/migrate_db/*, ...], exclusions=[/api/properties*, ...]}]
2018.04.19 16:31:23 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2018.04.19 16:31:25 INFO  web[][o.s.s.p.UpdateCenterClient] Update center: https://update.sonarsource.org/update-center.properties (no proxy)
2018.04.19 16:31:26 INFO  web[][o.s.s.e.IndexCreator] Create index metadatas
2018.04.19 16:31:27 INFO  web[][o.s.s.e.IndexCreator] Create type metadatas/metadata
2018.04.19 16:31:27 INFO  web[][o.s.s.e.IndexCreator] Create index components
2018.04.19 16:31:28 INFO  web[][o.s.s.e.IndexCreator] Create type components/component
2018.04.19 16:31:28 INFO  web[][o.s.s.e.IndexCreator] Create type components/authorization
2018.04.19 16:31:28 INFO  web[][o.s.s.e.IndexCreator] Create index tests
2018.04.19 16:31:28 INFO  web[][o.s.s.e.IndexCreator] Create type tests/test
2018.04.19 16:31:28 INFO  web[][o.s.s.e.IndexCreator] Create index projectmeasures
2018.04.19 16:31:28 INFO  web[][o.s.s.e.IndexCreator] Create type projectmeasures/projectmeasure
2018.04.19 16:31:28 INFO  web[][o.s.s.e.IndexCreator] Create type projectmeasures/authorization
2018.04.19 16:31:28 INFO  web[][o.s.s.e.IndexCreator] Create index rules
2018.04.19 16:31:29 INFO  web[][o.s.s.e.IndexCreator] Create type rules/activeRule
2018.04.19 16:31:29 INFO  web[][o.s.s.e.IndexCreator] Create type rules/ruleExtension
2018.04.19 16:31:29 INFO  web[][o.s.s.e.IndexCreator] Create type rules/rule
2018.04.19 16:31:29 INFO  web[][o.s.s.e.IndexCreator] Create index issues
2018.04.19 16:31:29 INFO  web[][o.s.s.e.IndexCreator] Create type issues/issue
2018.04.19 16:31:29 INFO  web[][o.s.s.e.IndexCreator] Create type issues/authorization
2018.04.19 16:31:29 INFO  web[][o.s.s.e.IndexCreator] Create index users
2018.04.19 16:31:29 INFO  web[][o.s.s.e.IndexCreator] Create type users/user
2018.04.19 16:31:29 INFO  web[][o.s.s.e.IndexCreator] Create index views
2018.04.19 16:31:29 INFO  web[][o.s.s.e.IndexCreator] Create type views/view
2018.04.19 16:31:30 INFO  web[][o.s.s.s.LogServerId] Server ID: AWLevwaimZTRbwDLht15
2018.04.19 16:31:30 INFO  web[][o.s.s.t.TelemetryDaemon] Sharing of SonarQube statistics is enabled.
2018.04.19 16:31:30 INFO  web[][o.s.s.n.NotificationDaemon] Notification service started (delay 60 sec.)
2018.04.19 16:31:30 INFO  web[][o.s.s.s.GeneratePluginIndex] Generate scanner plugin index
2018.04.19 16:31:30 INFO  web[][o.s.s.s.RegisterPlugins] Register plugins
2018.04.19 16:31:30 INFO  web[][o.s.s.s.RegisterMetrics] Register metrics
2018.04.19 16:31:31 INFO  web[][o.s.s.q.RegisterQualityGates] Built-in quality gate's conditions of [Sonar way] has been updated
2018.04.19 16:31:31 INFO  web[][o.s.s.r.RegisterRules] Register rules
2018.04.19 16:31:44 INFO  web[][o.s.s.q.BuiltInQProfileRepositoryImpl] Load quality profiles
2018.04.19 16:31:45 INFO  web[][o.s.s.q.RegisterQualityProfiles] Register quality profiles
2018.04.19 16:31:45 INFO  web[][o.s.s.q.RegisterQualityProfiles] Register profile cs/Sonar way



2018.04.19 16:36:19 WARN  web[][o.e.t.TransportService] Received response for a request that has timed out, sent [119669ms] ago, timed out [114136ms] ago, action [cluster:monitor/nodes/liveness], node [{#transport#-1}{1TGm_g8MTgmewqdX_Xv4Qg}{127.0.0.1}{127.0.0.1:9001}], id [89]


2018.04.19 16:37:48 INFO  web[][o.e.c.t.TransportClientNodesService] failed to get node info for {#transport#-1}{1TGm_g8MTgmewqdX_Xv4Qg}{127.0.0.1}{127.0.0.1:9001}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:9001][cluster:monitor/nodes/liveness] request_id [89] timed out after [5533ms]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:951)
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018.04.19 16:37:48 WARN  web[][o.e.a.b.BulkRequestHandler$SyncBulkRequestHandler] Failed to execute bulk request 1.
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{1TGm_g8MTgmewqdX_Xv4Qg}{127.0.0.1}{127.0.0.1:9001}]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
	at org.elasticsearch.client.support.AbstractClient.bulk(AbstractClient.java:485)
	at org.elasticsearch.action.bulk.Retry$RetryHandler.execute(Retry.java:230)
	at org.elasticsearch.action.bulk.Retry.withSyncBackoff(Retry.java:103)
	at org.elasticsearch.action.bulk.BulkRequestHandler$SyncBulkRequestHandler.execute(BulkRequestHandler.java:86)
	at org.elasticsearch.action.bulk.BulkProcessor.execute(BulkProcessor.java:350)
	at org.elasticsearch.action.bulk.BulkProcessor.awaitClose(BulkProcessor.java:231)
	at org.sonar.server.es.BulkIndexer.stop(BulkIndexer.java:110)
	at org.sonar.server.qualityprofile.index.ActiveRuleIndexer.doIndexActiveRules(ActiveRuleIndexer.java:166)
	at org.sonar.server.qualityprofile.index.ActiveRuleIndexer.index(ActiveRuleIndexer.java:143)
	at org.sonar.server.qualityprofile.index.ActiveRuleIndexer.postCommit(ActiveRuleIndexer.java:115)
	at org.sonar.server.qualityprofile.index.ActiveRuleIndexer.commitAndIndex(ActiveRuleIndexer.java:96)
	at org.sonar.server.qualityprofile.BuiltInQProfileInsertImpl.create(BuiltInQProfileInsertImpl.java:96)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.register(RegisterQualityProfiles.java:112)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.lambda$start$1(RegisterQualityProfiles.java:83)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.start(RegisterQualityProfiles.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:134)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:44)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:81)
	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:45)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:78)
	at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:196)
	at org.sonar.server.platform.Platform.access$400(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$1(Platform.java:121)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:121)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Thread.java:748)
2018.04.19 16:37:48 ERROR web[][o.s.s.es.BulkIndexer] Fail to execute bulk index request: org.elasticsearch.action.bulk.BulkRequest@d5ef56e
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{1TGm_g8MTgmewqdX_Xv4Qg}{127.0.0.1}{127.0.0.1:9001}]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
	at org.elasticsearch.client.support.AbstractClient.bulk(AbstractClient.java:485)
	at org.elasticsearch.action.bulk.Retry$RetryHandler.execute(Retry.java:230)
	at org.elasticsearch.action.bulk.Retry.withSyncBackoff(Retry.java:103)
	at org.elasticsearch.action.bulk.BulkRequestHandler$SyncBulkRequestHandler.execute(BulkRequestHandler.java:86)
	at org.elasticsearch.action.bulk.BulkProcessor.execute(BulkProcessor.java:350)
	at org.elasticsearch.action.bulk.BulkProcessor.awaitClose(BulkProcessor.java:231)
	at org.sonar.server.es.BulkIndexer.stop(BulkIndexer.java:110)
	at org.sonar.server.qualityprofile.index.ActiveRuleIndexer.doIndexActiveRules(ActiveRuleIndexer.java:166)
	at org.sonar.server.qualityprofile.index.ActiveRuleIndexer.index(ActiveRuleIndexer.java:143)
	at org.sonar.server.qualityprofile.index.ActiveRuleIndexer.postCommit(ActiveRuleIndexer.java:115)
	at org.sonar.server.qualityprofile.index.ActiveRuleIndexer.commitAndIndex(ActiveRuleIndexer.java:96)
	at org.sonar.server.qualityprofile.BuiltInQProfileInsertImpl.create(BuiltInQProfileInsertImpl.java:96)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.register(RegisterQualityProfiles.java:112)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.lambda$start$1(RegisterQualityProfiles.java:83)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.start(RegisterQualityProfiles.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:134)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:44)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:81)
	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:45)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:78)
	at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:196)
	at org.sonar.server.platform.Platform.access$400(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$1(Platform.java:121)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:121)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Thread.java:748)
2018.04.19 16:37:48 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{1TGm_g8MTgmewqdX_Xv4Qg}{127.0.0.1}{127.0.0.1:9001}]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
	at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:363)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
	at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1256)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
	at org.sonar.server.es.request.ProxyRefreshRequestBuilder.get(ProxyRefreshRequestBuilder.java:42)
	at org.sonar.server.es.request.ProxyRefreshRequestBuilder.get(ProxyRefreshRequestBuilder.java:32)
	at org.sonar.server.es.BulkIndexer.stop(BulkIndexer.java:115)
	at org.sonar.server.qualityprofile.index.ActiveRuleIndexer.doIndexActiveRules(ActiveRuleIndexer.java:166)
	at org.sonar.server.qualityprofile.index.ActiveRuleIndexer.index(ActiveRuleIndexer.java:143)
	at org.sonar.server.qualityprofile.index.ActiveRuleIndexer.postCommit(ActiveRuleIndexer.java:115)
	at org.sonar.server.qualityprofile.index.ActiveRuleIndexer.commitAndIndex(ActiveRuleIndexer.java:96)
	at org.sonar.server.qualityprofile.BuiltInQProfileInsertImpl.create(BuiltInQProfileInsertImpl.java:96)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.register(RegisterQualityProfiles.java:112)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.lambda$start$1(RegisterQualityProfiles.java:83)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.sonar.server.qualityprofile.RegisterQualityProfiles.start(RegisterQualityProfiles.java:80)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110)
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
	at org.picocontainer.behaviors.Stored.start(Stored.java:110)
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:134)
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:44)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:81)
	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:45)
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:78)
	at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:196)
	at org.sonar.server.platform.Platform.access$400(Platform.java:46)
	at org.sonar.server.platform.Platform$1.lambda$doRun$1(Platform.java:121)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
	at org.sonar.server.platform.Platform$1.doRun(Platform.java:121)
	at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
	at java.lang.Thread.run(Thread.java:748)
2018.04.19 16:37:49 INFO  web[][o.s.p.StopWatcher] Stopping process
2018.04.19 16:37:53 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2018.04.19 16:37:54 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
2018.04.19 16:37:54 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2018.04.19 16:37:54 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```

**Comment by Godin** [comment]
Similarly to #48 - if on a machine there is lack of resources such as CPU, then server will not start or will not function properly even if will be started.
