### ISSUE TITLE
unsafe memory access error on startup.

### ISSUE THREAD

**Issue by jcdalton2201** [SonarSource/docker-sonarqube#180]
I've tried both the latest and 6.7.3 versions and when i try to do a docker run i get the following error ```2018.06.01 12:46:22 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
Exception in thread "main" java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
at sun.misc.Unsafe.putByte(Native Method)
at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:306)
at org.sonar.process.sharedmemoryfile.AllProcessesCommands.writeByte(AllProcessesCommands.java:211)
at org.sonar.process.sharedmemoryfile.AllProcessesCommands.cleanData(AllProcessesCommands.java:206)
at org.sonar.process.sharedmemoryfile.AllProcessesCommands.clean(AllProcessesCommands.java:106)
at org.sonar.application.AppFileSystem.reset(AppFileSystem.java:64)
at org.sonar.application.App.start(App.java:55)
at org.sonar.application.App.main(App.java:78)``` i'm runing docker 18.03.1-ce on a mac.

**Comment by h-e-n-r-y** [comment]
I had the same error today.
It seems to be an out-of-memory problem of docker. Cleaning up unneeded containers and images helped.

`docker images --no-trunc | grep '<none>' | awk '{ print $3 }' | xargs docker rmi`

**Comment by janos-ss** [comment]
Is this still an issue with recent versions and the images? (We've just released new versions of the images)

**Comment by ArchanaChillala** [comment]
Faced the same issue with 7.6-community version as well, however, cleaning up some existing images and unused containers helped.

**Comment by pierre-guillot-sonarsource** [comment]
I'm closing this since there has been no update for a while. Please retry with the latest SQ version and create a new issue if needed, with more details and logs.

**Comment by jasonchester** [comment]
cleaning up space in docker for mac fixed this issue for me. I used the docker system prune command below.

```sh
docker system prune
```

**Comment by AvasDream** [comment]
What helped for me was deleting **all** my volumes: `docker volume rm $(docker volume ls -q)`
