### ISSUE TITLE
Problems with sonarqube and postgres with docker compose 

### ISSUE THREAD

**Issue by gabbosam** [SonarSource/docker-sonarqube#193]
Hi,
i have a problem running sonarqube and postgres with docker-compose.
I follow the documentation and the recipe but i'm unable to run sonarqube....

I'm able to run sonarqube with simple "docker run" command, and i tried it (amazing), but when i try with the docker-compose.yml file no.

here my yaml definition
```yaml

version: "3"

services:
  sonarqube:
    image: sonarqube:6.7.4
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=mypass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    ports:
      - "9100:9000"
      - "9192:9092"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres:10.4
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=mypass
      - POSTGRES_DB=sonarqube
    expose:
      - "5462"
    ports:
      - "5462:5432"
    volumes:
      - sonarqube_db:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_db:
  sonarqube_extensions:
```
I've done only little changes for the host port (default db port his owned by another postgres).

Running `docker-compose up -d` seems all ok, but when i try to connect to http://127.0.0.1:9100 the sonarqube container (sonarqube_sonarqube_1) seems to be killed.

Can you help me?

Thank you

------------
UPDATE:
seems to be an error with the db auth, here the docker logs
```
2018.08.06 15:03:59 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2018.08.06 15:03:59 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2018.08.06 15:03:59 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonarqube/temp/conf/es
2018.08.06 15:03:59 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2018.08.06 15:04:00 INFO  app[][o.e.p.PluginsService] no modules loaded
2018.08.06 15:04:00 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2018.08.06 15:04:12 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2018.08.06 15:04:12 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonarqube]: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -cp ./lib/common/*:./lib/server/*:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.2.1.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process3852790547695445976properties
2018.08.06 15:04:12 INFO  web[][o.s.p.ProcessEntryPoint] Starting web
2018.08.06 15:04:13 INFO  web[][o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
2018.08.06 15:04:14 INFO  web[][o.e.p.PluginsService] no modules loaded
2018.08.06 15:04:14 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.index.reindex.ReindexPlugin]
2018.08.06 15:04:14 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.join.ParentJoinPlugin]
2018.08.06 15:04:14 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.percolator.PercolatorPlugin]
2018.08.06 15:04:14 INFO  web[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2018.08.06 15:04:16 INFO  web[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [127.0.0.1:9001]
2018.08.06 15:04:16 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 6.7.4.38452 / b62b59da1adf991c41ed0730684f813d4116f6cc
2018.08.06 15:04:16 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://db:5432/sonarqube
2018.08.06 15:04:16 WARN  web[][unknown.jul.logger] SQLException occurred while connecting to db:5432
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "sonar"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:475)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:207)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:452)
	at org.postgresql.Driver.connect(Driver.java:254)
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
	at org.sonar.db.profiling.NullConnectionInterceptor.getConnection(NullConnectionInterceptor.java:31)
	at org.sonar.db.profiling.ProfiledDataSource.getConnection(ProfiledDataSource.java:323)
	at org.sonar.db.DefaultDatabase.checkConnection(DefaultDatabase.java:106)
	at org.sonar.db.DefaultDatabase.start(DefaultDatabase.java:75)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

----------
UPDATE
i remove my changes (leaving the host port mapping for the webserver) but i've got the same error within the db auth.

**Comment by Godin** [comment]
Please read https://docs.docker.com/compose/startup-order/ - database should be up and running before SonarQube.

Using your `docker-compose.yml`:

`docker-compose up db` waiting for appearance of

```
db_1         | 2018-08-06 16:32:05.240 UTC [1] LOG:  database system is ready to accept connections
```

and only then `docker-compose up sonarqube` results in successful startup

```
sonarqube_1  | 2018.08.06 16:33:05 INFO  app[][o.s.a.SchedulerImpl] SonarQube is up
```

**Comment by Godin** [comment]
Also this is not a Q/A forum. In future please use https://community.sonarsource.com/ for access to wider audiences of people who can help/answer than watchers of this repository. Thank you for your understanding.
