### ISSUE TITLE
alpine support for latest versions

### ISSUE THREAD

**Issue by jadolg** [SonarSource/docker-sonarqube#261]
Hi, I've been exploring the tags on [DockerHub](https://hub.docker.com/_/sonarqube?tab=tags) and I'm not able to find any recent build with alpine. The last alpine tag was **7.1-alpine** and the last community tag was **7.7-community**.
I tried even switching to **7.7-community** but there are not compatible.
Do you have any plans to update on alpine? 
If not, are there any guides to cook my own image?

**Comment by mwz** [comment]
You can find the answer here https://github.com/SonarSource/docker-sonarqube/blob/c210439c9e6389d64e43f65ab3404bf55c1ed9b7/develop.md#faq

**Comment by jadolg** [comment]
Thanks for your fast answer :)
Back to it, is there a way to migrate from the alpine based to the regular one?

**Comment by mwz** [comment]
Unless you're building on top of the image and using alpine specific things, from my personal experience, it should be just the case of swapping out the images.
If you're mounting any volumes from other containers, you might have to tweak the permissions as the entrypoint now runs under the `sonarqube` user (see [here](https://github.com/SonarSource/docker-sonarqube/blob/05038494ed698da79be5afcacb7a02cfb56e4c7b/7.7-community/Dockerfile#L51)).

**Comment by jadolg** [comment]
After moving to the new image I'm getting this error which I'm not really sure is a permissions problem:
```
sonarqube_1  | 2019.04.03 17:30:56 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
sonarqube_1  | 2019.04.03 17:30:56 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
sonarqube_1  | 2019.04.03 17:30:56 INFO  app[][o.s.a.p.ProcessLauncherImpl] Deleting outdated search index data directory /opt/sonarqube/data/es5                                                                                                                            
sonarqube_1  | 2019.04.03 17:30:56 INFO  app[][o.s.a.p.ProcessLauncherImpl] Failed to delete outdated search index data directory /opt/sonarqube/data/es5                                                                                                                    
sonarqube_1  | java.nio.file.AccessDeniedException: /opt/sonarqube/data/es5/nodes/0/indices/G6kzHCUQTyOwY1k82Otk6w/1/_state/state-98.st                                                                                                                                      
sonarqube_1  |  at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
sonarqube_1  |  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
sonarqube_1  |  at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
sonarqube_1  |  at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
sonarqube_1  |  at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
sonarqube_1  |  at java.nio.file.Files.delete(Files.java:1126)
sonarqube_1  |  at org.sonar.process.FileUtils2$DeleteRecursivelyFileVisitor.visitFile(FileUtils2.java:186)
sonarqube_1  |  at org.sonar.process.FileUtils2$DeleteRecursivelyFileVisitor.visitFile(FileUtils2.java:181)
sonarqube_1  |  at java.nio.file.Files.walkFileTree(Files.java:2670)
sonarqube_1  |  at java.nio.file.Files.walkFileTree(Files.java:2742)
sonarqube_1  |  at org.sonar.process.FileUtils2.deleteDirectoryImpl(FileUtils2.java:143)
sonarqube_1  |  at org.sonar.process.FileUtils2.deleteDirectory(FileUtils2.java:112)
sonarqube_1  |  at org.sonar.application.process.ProcessLauncherImpl.lambda$cleanupOutdatedEsData$1(ProcessLauncherImpl.java:129)
sonarqube_1  |  at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
sonarqube_1  |  at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
sonarqube_1  |  at org.sonar.application.process.ProcessLauncherImpl.cleanupOutdatedEsData(ProcessLauncherImpl.java:125)
sonarqube_1  |  at org.sonar.application.process.ProcessLauncherImpl.launch(ProcessLauncherImpl.java:80)
sonarqube_1  |  at org.sonar.application.SchedulerImpl.lambda$tryToStartProcess$2(SchedulerImpl.java:154)
sonarqube_1  |  at org.sonar.application.process.SQProcess.start(SQProcess.java:68)
sonarqube_1  |  at org.sonar.application.SchedulerImpl.tryToStart(SchedulerImpl.java:160)
sonarqube_1  |  at org.sonar.application.SchedulerImpl.tryToStartProcess(SchedulerImpl.java:152)
sonarqube_1  |  at org.sonar.application.SchedulerImpl.tryToStartEs(SchedulerImpl.java:110)
sonarqube_1  |  at org.sonar.application.SchedulerImpl.tryToStartAll(SchedulerImpl.java:102)
sonarqube_1  |  at org.sonar.application.SchedulerImpl.schedule(SchedulerImpl.java:98)
sonarqube_1  |  at org.sonar.application.App.start(App.java:64)
sonarqube_1  |  at org.sonar.application.App.main(App.java:78)
sonarqube_1  | 2019.04.03 17:30:56 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch                                                 
sonarqube_1  | 2019.04.03 17:30:56 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
sonarqube_1  | 2019.04.03 17:30:57 INFO  app[][o.e.p.PluginsService] no modules loaded
sonarqube_1  | 2019.04.03 17:30:57 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
sonarqube_1  | 2019.04.03 17:30:59 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 1
sonarqube_1  | 2019.04.03 17:30:59 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
sonarqube_1  | 2019.04.03 17:30:59 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```

**Comment by jadolg** [comment]
@mwz So yes, it was exactly that.
I started the 7.7-community as root and changed the owner of the files on the volumes and then started sonar normally and it started working.
Well, not exactly... I had to manually delete plugins that were not compatible, but I lost no data and that's great.
Thanks for your help :-)
