### ISSUE TITLE
Error when starting sonarqube in docker as per readme instructions

### ISSUE THREAD

**Issue by andrei-dascalu** [SonarSource/docker-sonarqube#269]
Hello,

When running `docker run -d --name sonarqube -p 9000:9000 sonarqube ` the result is:

```
2019.05.20 10:31:25 ERROR web[][o.s.s.es.BulkIndexer] index [rules], type [rule], id [ar_1533], message [ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]]
2019.05.20 10:31:25 ERROR web[][o.s.s.es.BulkIndexer] index [rules], type [rule], id [ar_1534], message [ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]]
2019.05.20 10:31:25 ERROR web[][o.s.s.es.BulkIndexer] index [rules], type [rule], id [ar_1535], message [ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]]
2019.05.20 10:31:25 ERROR web[][o.s.s.es.BulkIndexer] index [rules], type [rule], id [ar_1536], message [ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]]
2019.05.20 10:31:25 ERROR web[][o.s.s.es.BulkIndexer] index [rules], type [rule], id [ar_1537], message [ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]]
2019.05.20 10:31:25 ERROR web[][o.s.s.es.BulkIndexer] index [rules], type [rule], id [ar_1538], message [ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]]
2019.05.20 10:31:25 ERROR web[][o.s.s.es.BulkIndexer] index [rules], type [rule], id [ar_1539], message [ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]]
2019.05.20 10:31:25 ERROR web[][o.s.s.es.BulkIndexer] index [rules], type [rule], id [ar_1540], message [ClusterBlockException[blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];]]
2019.05.20 10:31:25 INFO  web[][o.s.s.s.RegisterPermissionTemplates] Register permission templates
2019.05.20 10:31:25 INFO  web[][o.s.s.s.RenameDeprecatedPropertyKeys] Rename deprecated property keys
2019.05.20 10:31:25 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.ws.WebServiceFilter@4076a360 [pattern=UrlPattern{inclusions=[/api/issues/delete_comment.*, ...], exclusions=[/api/properties*, ...]}]
2019.05.20 10:31:25 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.ws.DeprecatedPropertiesWsFilter@3fa8fb90 [pattern=UrlPattern{inclusions=[/api/properties/*], exclusions=[]}]
2019.05.20 10:31:25 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.ws.WebServiceReroutingFilter@1861d2f3 [pattern=UrlPattern{inclusions=[/api/components/bulk_update_key, ...], exclusions=[]}]
2019.05.20 10:31:25 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.InitFilter@5b60776d [pattern=UrlPattern{inclusions=[/sessions/init/*], exclusions=[]}]
2019.05.20 10:31:25 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.OAuth2CallbackFilter@45a6d70a [pattern=UrlPattern{inclusions=[/oauth2/callback/*], exclusions=[]}]
2019.05.20 10:31:25 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.ws.LoginAction@133671d0 [pattern=UrlPattern{inclusions=[/api/authentication/login], exclusions=[]}]
2019.05.20 10:31:25 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.ws.LogoutAction@7315ba [pattern=UrlPattern{inclusions=[/api/authentication/logout], exclusions=[]}]
2019.05.20 10:31:25 INFO  web[][o.s.s.p.w.MasterServletFilter] Initializing servlet filter org.sonar.server.authentication.ws.ValidateAction@46de0f05 [pattern=UrlPattern{inclusions=[/api/authentication/validate], exclusions=[]}]
2019.05.20 10:31:25 INFO  web[][o.s.s.e.IndexerStartupTask] Indexing of type [rules/rule/activeRule] ...
2019.05.20 10:31:25 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
org.elasticsearch.cluster.block.ClusterBlockException: blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];
	at org.elasticsearch.cluster.block.ClusterBlocks.indicesBlockedException(ClusterBlocks.java:204)
	at org.elasticsearch.action.admin.indices.settings.put.TransportUpdateSettingsAction.checkBlock(TransportUpdateSettingsAction.java:73)
	at org.elasticsearch.action.admin.indices.settings.put.TransportUpdateSettingsAction.checkBlock(TransportUpdateSettingsAction.java:41)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.doStart(TransportMasterNodeAction.java:173)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction.start(TransportMasterNodeAction.java:164)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:141)
	at org.elasticsearch.action.support.master.TransportMasterNodeAction.doExecute(TransportMasterNodeAction.java:59)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:167)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:139)
	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:83)
	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:73)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:66)
	at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1289)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:140)
	at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1247)
	at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1111)
	at org.elasticsearch.transport.TcpTransport.inboundMessage(TcpTransport.java:914)
	at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:53)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:656)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:556)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:470)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
	at java.lang.Thread.run(Thread.java:748)
2019.05.20 10:31:25 INFO  web[][o.s.p.StopWatcher] Stopping process
2019.05.20 10:31:26 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2019.05.20 10:31:27 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2019.05.20 10:31:27 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
2019.05.20 10:31:27 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
```

This could be related to https://github.com/SonarSource/docker-sonarqube/issues/251 though the processes and exit value seem different.

Client info:

```
Client: Docker Engine - Community
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        6247962
 Built:             Sun Feb 10 04:12:39 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       6247962
  Built:            Sun Feb 10 04:13:06 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

Cheers

**Comment by polibenitez** [comment]
+1

**Comment by sooncj** [comment]
My disk was over threshold for ES the first time I started sonar.
I had to increase free disk space on the host and delete the data volume, per:
https://discuss.elastic.co/t/forbidden-12-index-read-only-allow-delete-api/110282/2

ES default disk watermark is 90% (that's 90% on the host disk of the volume):
https://www.elastic.co/guide/en/elasticsearch/reference/current/disk-allocator.html

**Comment by pierre-guillot-sonarsource** [comment]
Please take a look at the [requirements](https://docs.sonarqube.org/latest/requirements/requirements/) and get back to us with more detail if needed

**Comment by geyuqiu** [comment]
I stoped all docker containers, and deleted all docker images. Then the error is not coming any more

**Comment by serut** [comment]
If you do not want to loose data, you can reenable ES write : 
```
docker-compose exec sonarqube curl -X PUT "localhost:9100/_all/_settings" -H 'Content-Type: application/json' -d'{ "index": {"blocks.read_only" : false } }'
```
I'm posting it here as it is the first result on google...

**Comment by pierre-guillot-sonarsource** [comment]
The ES index is rebuilt at startup from the database if needed. There is no data loss.

**Comment by serut** [comment]
Good to know !
