### ISSUE TITLE
The host [HOSTNAME_9000] is not valid

### ISSUE THREAD

**Issue by technomatic** [SonarSource/docker-sonarqube#274]
Hi ,

appreciate some one help on this issue, using 6.7.7 and 7.7 community edition of docker sonar qube and we are getting below error after sonarqube start up and browser is giving 400 error. not exactly sure whats the root cause.

2019.06.14 09:09:14 INFO  ce[][o.s.ce.app.CeServer] Compute Engine is operational
2019.06.14 09:09:14 INFO  app[][o.s.a.SchedulerImpl] Process[ce] is up
2019.06.14 09:09:14 INFO  app[][o.s.a.SchedulerImpl] SonarQube is up
2019.06.14 09:09:40 INFO  web[][o.a.c.h.Http11Processor] The host [HOSTNAME_9000] is not valid
 Note: further occurrences of request parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: The character [_] is never valid in a domain name.
        at org.apache.tomcat.util.http.parser.HttpParser$DomainParseState.next(HttpParser.java:946)
        at org.apache.tomcat.util.http.parser.HttpParser.readHostDomainName(HttpParser.java:842)
        at org.apache.tomcat.util.http.parser.Host.parse(Host.java:66)
        at org.apache.tomcat.util.http.parser.Host.parse(Host.java:40)
        at org.apache.coyote.AbstractProcessor.parseHost(AbstractProcessor.java:292)
        at org.apache.coyote.http11.Http11Processor.prepareRequest(Http11Processor.java:1203)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:776)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by vernou** [comment]
I have the same error.
@technomatic, did you manage to solve this problem?

**Comment by vernou** [comment]
In my case, it's our reverse proxy that redefines the header "Host" with the upstream (that contains a "_").
