### ISSUE TITLE
Sonar 7.9 doesn't start with docker

### ISSUE THREAD

**Issue by WizaXxX** [SonarSource/docker-sonarqube#345]
I went to https://hub.docker.com/_/sonarqube and did to all instructions:
```
docker pull sonarqube
sysctl -w vm.max_map_count=262144
sysctl -w fs.file-max=65536
ulimit -n 65536
ulimit -u 4096
sudo systemctl restart docker.service 
mkdir /path/to/your/filesystem/sonarqube_home
export SONARQUBE_HOME=/path/to/your/filesystem/sonarqube_home
docker run --rm \
-v $SONARQUBE_HOME/conf:/opt/sonarqube/conf \
-v $SONARQUBE_HOME/extensions:/opt/sonarqube/extensions \
-v $SONARQUBE_HOME/data:/opt/sonarqube/data \
sonarqube --init
```
but i got a error msg

```
wizaxxx@ubuntu ~/test> docker run --rm \
                       -v $SONARQUBE_HOME/conf:/opt/sonarqube/conf \
                       -v $SONARQUBE_HOME/extensions:/opt/sonarqube/extensions \
                       -v $SONARQUBE_HOME/data:/opt/sonarqube/data \
                       sonarqube --init
tail: cannot open './logs/es.log' for reading: No such file or directory
14:21:19.615 [main] WARN org.sonar.application.config.AppSettingsLoaderImpl - Configuration file not found: /opt/sonarqube/conf/sonar.properties
Exception in thread "main" java.lang.IllegalArgumentException: Command-line argument must start with -D, for example -Dsonar.jdbc.username=sonar. Got: --init
        at org.sonar.application.config.CommandLineParser.argumentsToProperties(CommandLineParser.java:56)
        at org.sonar.application.config.CommandLineParser.parseArguments(CommandLineParser.java:37)
        at org.sonar.application.config.AppSettingsLoaderImpl.load(AppSettingsLoaderImpl.java:66)
        at org.sonar.application.App.start(App.java:51)
        at org.sonar.application.App.main(App.java:98)
```

help me please :) what did i do wrong?

**Comment by pierre-guillot-sonarsource** [comment]
Hello,

Current documentation is valid for beta images. Please use the `sonarqube:8.0-community-beta` tag.

LTS and 7.X version don't have this --init instruction

**Comment by WizaXxX** [comment]
thank, but i think you need to fix instructions.
but without --init also didn't start

```
wizaxxx@ubuntu ~/test> docker run --rm \
                         -v /home/wizaxxx/test/sonar/sonar/conf:/opt/sonarqube/conf \
                         -v /home/wizaxxx/test/sonar/sonar/extensions:/opt/sonarqube/extensions \
                         -v /home/wizaxxx/test/sonar/sonar/data:/opt/sonarqube/data \
                         sonarqube
tail: cannot open './logs/es.log' for reading: No such file or directory
14:38:13.329 [main] WARN org.sonar.application.config.AppSettingsLoaderImpl - Configuration file not found: /opt/sonarqube/conf/sonar.properties
2019.11.07 14:38:13 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2019.11.07 14:38:13 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2019.11.07 14:38:13 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch
2019.11.07 14:38:13 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2019.11.07 14:38:13 INFO  app[][o.e.p.PluginsService] no modules loaded
2019.11.07 14:38:13 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
2019.11.07 14:38:14 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 1
2019.11.07 14:38:14 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2019.11.07 14:38:14 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```

**Comment by pierre-guillot-sonarsource** [comment]
Do you explicitly need to run the LTS, or you can be on the latest 8.0 version ?

**Comment by WizaXxX** [comment]
I explicitly need to run the LTS :) because my plugin work on LTS  and doesn't work on 8 at the moment.

**Comment by pierre-guillot-sonarsource** [comment]
Ok. I agree the doc is crap and need to be updated, i will open a PR on the doc to specify what need to be done for the LTS vs the 8.0 version. We totally missed that, thanks for your feedback. In the meanwhile, you can browse the previous Readme.md version here : https://github.com/docker-library/docs/blob/869fe5a3a34201fa3def36399dc92f1f7f362b24/sonarqube/README.md

Few information about this documentation :
- usage of `-e sonar.jdbc.*` parameter is mandatory due to [SONAR-12501](https://jira.sonarsource.com/browse/SONAR-12501). This is not fixed for LTS version
- Your current error is indicating that the `conf/sonar.properties` file is missing. The LTS version is made to be used with volume instead of direct folder binding (you are getting a permission issue).

**Comment by WizaXxX** [comment]
thank you, it was help me. But after i create a conf/sonar.properties sonar didn't start and when i used chmod -R 777 to $SONARQUBE HOME it is started

**Comment by ndubbala** [comment]
> thank you, it was help me. But after i create a conf/sonar.properties sonar didn't start and when i used chmod -R 777 to $SONARQUBE HOME it is started

Hi Could you explain me what exactly you did  for resolution ?

**Comment by WizaXxX** [comment]
Hi, sorry but i don't remember which problems i had with this moment.
Probably, with access to `$SONARQUBE HOME`. Command `chmod -R 777` give recursive access to all user to this directory.
