### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by hemantshelar** [SonarSource/docker-sonarqube#377]
HI,
I am trying to setup community version of SonarQube on my dev machine using [this link](https://docs.sonarqube.org/latest/setup/get-started-2-minutes/)

Below is the snap
![image](https://user-images.githubusercontent.com/21121167/76713341-1e461c80-6774-11ea-81c8-7f22b9fa397f.png)

**Steps to reproduce**

1. Download sonarqube community version 8.2-community or 7.9-community
`docker pull sonarcube:8.2-community`  or 
`docker pull sonarcube:7.9-community`
2. create a container 
`docker run -d --name sonarqube -p 9000:9000 <image id>`
3. Login using default user name password ( admin/admin ) and create a test project
4. Begin sonar quebe
`SonarScanner.MSBuild.exe begin /k:"TestSonarQube" /d:sonar.host.url="http://localhost:9000" /d:sonar.login="637e1661ada054939319137e6cf89868c5d9cd78"`
5. Ms Build 
`"c:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" /t:Rebuild `
6. End Sonar Qube
`SonarScanner.MSBuild.exe end /d:sonar.login="0c22ad6c1afe4b7719f8fdd70cf4b18de5a691f5"`

I am not able to successfully complete step 6.  Upon executing step 6 , I am getting error `Unsupported major.minor version 52.0`

Below is entire stack trace.

`java.lang.UnsupportedClassVersionError: org/sonarsource/scanner/cli/Main : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Exception in thread "main"
The SonarQube Scanner did not complete successfully
10:39:55.374  Post-processing failed. Exit code: 1`

Am I missing anything?
Thanks

**Comment by hemantshelar** [comment]
It looks like we need to have java 8 installed on dev machine.  Nothing wrong with docker image.

**Comment by pragneshmpatel** [comment]
hi @hemantshelar ,
I have java installed still getting same error.  Do you know which version of java you have on dev machine?
![image](https://user-images.githubusercontent.com/1867062/88821865-133bd800-d1bb-11ea-88b4-5d2329f199c2.png)
