### ISSUE TITLE
LDAP plugin isno longer compatible with SonarQube - Enterprise version 8.2 

### ISSUE THREAD

**Issue by swingders** [SonarSource/docker-sonarqube#386]
Hello,
We are running sonarqube enterprise version 8.2 Docker container as a Pod on Openshift cluster. But the server start fails due to incompatible version of LDAP plugin. Please find below the error log for your reference. We use LDAP to manage authentication and authorization to the SonarQube server in our enterprise. Could you please let us know if you would release a new version of the LDAP plugin?

****Error Log****
2020.03.26 11:19:21 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
org.sonar.api.utils.MessageException: Plugins 'LDAP' are no longer compatible with this version of SonarQube. Refer to https://docs.sonarqube.org/latest/instance-administration/plugin-version-matrix/ 
2020.03.26 11:19:21 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
2020.03.26 11:19:22 WARN  web[][o.s.p.ProcessEntryPoint$HardStopperThread] Can not stop in 1000ms
2020.03.26 11:19:22 WARN  web[][o.s.s.a.EmbeddedTomcat] Failed to stop web server
org.apache.catalina.LifecycleException: Failed to stop component [StandardServer[-1]]
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:238)
	at org.apache.catalina.startup.Tomcat.stop(Tomcat.java:437)
	at org.sonar.server.app.EmbeddedTomcat.terminate(EmbeddedTomcat.java:104)
	at org.sonar.server.app.WebServer.hardStop(WebServer.java:83)
	at org.sonar.process.ProcessEntryPoint$HardStopperThread.lambda$new$0(ProcessEntryPoint.java:219)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.catalina.LifecycleException: Failed to stop component [StandardService[Tomcat]]
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:238)
	at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:814)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
	... 9 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to stop component [StandardEngine[Tomcat]]
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:238)
	at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:486)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
	... 11 common frames omitted
Caused by: org.apache.catalina.LifecycleException: A child container failed during stop
	at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:1008)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
	... 13 common frames omitted
2020.03.26 11:19:22 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
2020.03.26 11:19:23 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2020.03.26 11:19:23 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
2020.03.26 11:19:23 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 143

**Comment by pierre-guillot-sonarsource** [comment]
Hello, LDAP plugin is now embedded starting with SQ 8.0 : https://docs.sonarqube.org/latest/setup/upgrade-notes/#header-3

So just remove the plugin & enjoy :)

**Comment by swingders** [comment]
Thank you for your reply. It works after removing the plugin.
