### ISSUE TITLE
Restart sonarqube failing when it is mounted on azure fileshare

### ISSUE THREAD

**Issue by mimounchikhi** [SonarSource/docker-sonarqube#415]
Hi, we are using 7.9.3-community image.  It is deployed to k8s environment via a helm chart.  The tmp, logs, data, extensions are mountzed on a azure fileshare.
It is crashing when we need to restart the server.
Here is the log:
2020.07.03 07:37:22 INFO  es[][o.e.g.GatewayService] recovered [7] indices into cluster_state
2020.07.03 07:37:59 ERROR app[][o.s.a.p.EsManagedProcess] Failed to check status
java.lang.IllegalStateException: ClusterService was close during health call
	at org.elasticsearch.action.admin.cluster.health.TransportClusterHealthAction$3.onClusterServiceClose(TransportClusterHealthAction.java:190)
	at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onClusterServiceClose(ClusterStateObserver.java:315)
	at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onClose(ClusterStateObserver.java:234)
	at org.elasticsearch.cluster.service.ClusterApplierService.doStop(ClusterApplierService.java:173)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:91)
	at org.elasticsearch.cluster.service.ClusterService.doStop(ClusterService.java:123)
	at org.elasticsearch.common.component.AbstractLifecycleComponent.stop(AbstractLifecycleComponent.java:91)
	at org.elasticsearch.node.Node.stop(Node.java:848)
	at org.elasticsearch.node.Node.close(Node.java:871)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:103)
	at org.elasticsearch.core.internal.io.IOUtils.close(IOUtils.java:61)
	at org.elasticsearch.bootstrap.Bootstrap$4.run(Bootstrap.java:184)

This is only fixed when we remove the indices at /opt/sonarqube/data/es6/nodes/0/indices.
And this doesn't happen when it is mounted on a node share.

Any hints ?
Thx

**Comment by tobias-trabelsi-sonarsource** [comment]
Hi @mimounchikhi ,

Azure Fileshare in known to cause problems with sonarqube. as we just recently added support for k8s we already marked this as something worth investigating but for now i suggest that you update to our latest LTS release (8.9.1) and use a different storage class for sonarqube. also we have a [helm chart](https://github.com/SonarSource/helm-chart-sonarqube/tree/master/charts/sonarqube) now :) 

If you need additional help, there are multiple threads regarding this problem in our [community forum](https://community.sonarsource.com/) that you might be interested in

**Comment by brecht-vermeersch** [comment]
any update on this?
