### ISSUE TITLE
Scanner gives an error "You must define the following mandatory properties for 'Unknown': sonar.projectKey" when sonar.projectKey is injected

### ISSUE THREAD

**Issue by lcabahug** [SonarSource/docker-sonarqube#449]
Sonarqube cannot perform analysis on a Java project and fails when sonar-project.properties file is missing but sonar.projectKey is injected as parameter.

**Expected Behavior:**
Sonarqube should be able to identify the project key from the -Dsonar.projectKey argument passed in the scanner, and start the scan.
Source: https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/
![sonarscanner-snippet](https://user-images.githubusercontent.com/72370355/100005433-db3b4f00-2dc0-11eb-9949-eb02e1c9ce63.png)

**Actual Behavior:**
The scanner fails and gives the message "You must define the following mandatory properties for 'Unknown': sonar.projectKey"
Please see logs for more details.

**Pipeline Logs:**
> ```
> [Pipeline] stage
> [Pipeline] { (Static Analysis)
> [Pipeline] tool
> [Pipeline] envVarsForTool
> [Pipeline] tool
> [Pipeline] envVarsForTool
> [Pipeline] tool
> [Pipeline] envVarsForTool
> [Pipeline] tool
> 
> [Pipeline] envVarsForTool
> [Pipeline] withEnv
> [Pipeline] {
> [Pipeline] script
> [Pipeline] {
> [Pipeline] tool
> [Pipeline] withSonarQubeEnv
> Injecting SonarQube environment variables using the configuration: sonarqube-local
> [Pipeline] {
> [Pipeline] sh
> + /var/jenkins_home/tools/hudson.plugins.sonar.SonarRunnerInstallation/sonar-scanner4.5/bin/sonar-scanner -X
> 19:28:04.028 INFO: Scanner configuration file: /var/jenkins_home/tools/hudson.plugins.sonar.SonarRunnerInstallation/sonar-scanner4.5/conf/sonar-scanner.properties
> 19:28:04.030 INFO: Project root configuration file: NONE
> 19:28:04.046 INFO: SonarScanner 4.5.0.2216
> 19:28:04.046 INFO: Java 11.0.9 AdoptOpenJDK (64-bit)
> 19:28:04.046 INFO: Linux 4.18.0-193.28.1.el8_2.x86_64 amd64
> 19:28:04.122 DEBUG: keyStore is : 
> 19:28:04.122 DEBUG: keyStore type is : pkcs12
> 19:28:04.122 DEBUG: keyStore provider is : 
> 19:28:04.122 DEBUG: init keystore
> 19:28:04.122 DEBUG: init keymanager of type SunX509
> 19:28:04.194 DEBUG: Create: /var/jenkins_home/.sonar/cache
> 19:28:04.194 INFO: User cache: /var/jenkins_home/.sonar/cache
> 19:28:04.194 DEBUG: Create: /var/jenkins_home/.sonar/cache/_tmp
> 19:28:04.195 DEBUG: Extract sonar-scanner-api-batch in temp...
> 19:28:04.197 DEBUG: Get bootstrap index...
> 19:28:04.197 DEBUG: Download: http://sonarqube:9000/batch/index
> 19:28:04.228 DEBUG: Get bootstrap completed
> 19:28:04.230 DEBUG: Create isolated classloader...
> 19:28:04.235 DEBUG: Start temp cleaning...
> 19:28:04.237 DEBUG: Temp cleaning done
> 19:28:04.237 INFO: Scanner configuration file: /var/jenkins_home/tools/hudson.plugins.sonar.SonarRunnerInstallation/sonar-scanner4.5/conf/sonar-scanner.properties
> 19:28:04.237 INFO: Project root configuration file: NONE
> 19:28:04.238 DEBUG: Execution getVersion
> 19:28:04.247 INFO: Analyzing on SonarQube server 8.5.1
> 19:28:04.248 INFO: Default locale: "en", source code encoding: "UTF-8" (analysis is platform dependent)
> 19:28:04.248 DEBUG: Work directory: /var/jenkins_home/workspace/peline_feature_jenkinsFileUpdate/.scannerwork
> 19:28:04.249 DEBUG: Execution execute
> 19:28:04.380 DEBUG: Community 8.5.1.38104
> 19:28:04.437 INFO: Load global settings
> 19:28:04.456 DEBUG: GET 200 http://sonarqube:9000/api/settings/values.protobuf | time=19ms
> 19:28:04.477 INFO: Load global settings (done) | time=40ms
> 19:28:04.478 INFO: Server id: 46AF5D23-AXX0mJfm0Hc57P8jmdz9
> 19:28:04.480 INFO: User cache: /var/jenkins_home/.sonar/cache
> 19:28:04.481 INFO: Load/download plugins
> 19:28:04.481 INFO: Load plugins index
> 19:28:04.486 DEBUG: GET 200 http://sonarqube:9000/api/plugins/installed | time=5ms
> 19:28:04.506 INFO: Load plugins index (done) | time=25ms
> 19:28:04.545 INFO: Load/download plugins (done) | time=64ms
> 19:28:04.571 DEBUG: Plugins:
> 19:28:04.572 DEBUG:   * Python Code Quality and Security 3.1.0.7619 (python)
> 19:28:04.572 DEBUG:   * CSS Code Quality and Security 1.3.1.1642 (cssfamily)
> 19:28:04.572 DEBUG:   * JaCoCo 1.1.0.898 (jacoco)
> 19:28:04.572 DEBUG:   * SonarGo 1.6.0.719 (go)
> 19:28:04.572 DEBUG:   * SonarKotlin 1.5.0.315 (kotlin)
> 19:28:04.572 DEBUG:   * JavaScript/TypeScript Code Quality and Security 6.5.0.13383 (javascript)
> 19:28:04.572 DEBUG:   * SonarRuby 1.5.0.315 (ruby)
> 19:28:04.572 DEBUG:   * SonarScala 1.5.0.315 (sonarscala)
> 19:28:04.572 DEBUG:   * C# Code Quality and Security 8.13.1.21947 (csharp)
> 19:28:04.572 DEBUG:   * Java Code Quality and Security 6.8.0.23379 (java)
> 19:28:04.572 DEBUG:   * SonarHTML 3.2.0.2082 (web)
> 19:28:04.572 DEBUG:   * SonarFlex 2.5.1.1831 (flex)
> 19:28:04.572 DEBUG:   * SonarXML 2.0.1.2020 (xml)
> 19:28:04.572 DEBUG:   * PHP Code Quality and Security 3.9.0.6331 (php)
> 19:28:04.573 DEBUG:   * VB.NET Code Quality and Security 8.13.1.21947 (vbnet)
> 
> 19:28:04.828 INFO: Process project properties
> 19:28:04.832 INFO: ------------------------------------------------------------------------
> 19:28:04.832 INFO: EXECUTION FAILURE
> 19:28:04.832 INFO: ------------------------------------------------------------------------
> 19:28:04.832 INFO: Total time: 0.822s
> 19:28:04.842 INFO: Final Memory: 5M/34M
> 19:28:04.842 INFO: ------------------------------------------------------------------------
> 19:28:04.842 ERROR: Error during SonarScanner execution
> java.lang.IllegalStateException: Unable to load component class org.sonar.scanner.scan.ProjectLock
> 	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:66)
> 	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:678)
> 	at org.sonar.core.platform.ComponentContainer.getComponentByType(ComponentContainer.java:282)
> 	at org.sonar.scanner.scan.ProjectScanContainer.doBeforeStart(ProjectScanContainer.java:155)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
> 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
> 	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:144)
> 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:137)
> 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:123)
> 	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
> 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
> 	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
> 	at com.sun.proxy.$Proxy0.execute(Unknown Source)
> 	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
> 	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
> 	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
> 	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
> 	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
> Caused by: java.lang.IllegalStateException: Unable to load component class org.sonar.api.batch.fs.internal.DefaultInputProject
> 	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:66)
> 	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
> 	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
> 	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
> 	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
> 	at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
> 	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
> 	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
> 	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
> 	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
> 	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
> 	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
> 	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
> 	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
> 	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:64)
> 	... 22 more
> Caused by: java.lang.IllegalStateException: Unable to load component class org.sonar.api.batch.bootstrap.ProjectReactor
> 	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:66)
> 	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
> 	at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
> 	at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
> 	at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
> 	at org.picocontainer.injectors.SingleMemberInjector.getMemberArguments(SingleMemberInjector.java:61)
> 	at org.picocontainer.injectors.MethodInjector.getMemberArguments(MethodInjector.java:100)
> 	at org.picocontainer.injectors.MethodInjector$2.run(MethodInjector.java:112)
> 	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
> 	at org.picocontainer.injectors.MethodInjector.decorateComponentInstance(MethodInjector.java:120)
> 	at org.picocontainer.injectors.CompositeInjector.decorateComponentInstance(CompositeInjector.java:58)
> 	at org.picocontainer.injectors.Reinjector.reinject(Reinjector.java:142)
> 	at org.picocontainer.injectors.ProviderAdapter.getComponentInstance(ProviderAdapter.java:96)
> 	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
> 	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
> 	at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:64)
> 	... 36 more
> Caused by: You must define the following mandatory properties for 'Unknown': sonar.projectKey
> [Pipeline] }
> [Pipeline] // withSonarQubeEnv
> [Pipeline] }
> [Pipeline] // script
> Post stage
> [Pipeline] echo
> TODO(failure and unstable only) send notification to slack
> [Pipeline] }
> [Pipeline] // withEnv
> [Pipeline] }
> [Pipeline] // stage
> ```

**Below is my environment:**

**sonar-project.properties file**
None

**Jenkinsfile:**
```
pipeline {

  agent any

  environment {
    PROJ_VERSION = 0.1
  }

  stages {
    stage('Build') {
      steps {
        echo 'Building the application...'
        sh 'mvn -Dmaven.test.failure.ignore=true clean verify -Ptest'
      }
      post {
        success {
          junit 'target/surefire-reports/**/*.xml'
          jacoco changeBuildStatus: true, maximumBranchCoverage: '60', maximumClassCoverage: '90', maximumComplexityCoverage: '60', maximumInstructionCoverage: '60', maximumLineCoverage: '70', maximumMethodCoverage: '70', minimumBranchCoverage: '50', minimumClassCoverage: '80', minimumComplexityCoverage: '50', minimumInstructionCoverage: '50', minimumLineCoverage: '50', minimumMethodCoverage: '50'
        }
        failure {
          junit 'target/surefire-reports/**/*.xml'
          jacoco changeBuildStatus: true, maximumBranchCoverage: '60', maximumClassCoverage: '90', maximumComplexityCoverage: '60', maximumInstructionCoverage: '60', maximumLineCoverage: '70', maximumMethodCoverage: '70', minimumBranchCoverage: '50', minimumClassCoverage: '80', minimumComplexityCoverage: '50', minimumInstructionCoverage: '50', minimumLineCoverage: '50', minimumMethodCoverage: '50'
        }
      }
    }

    stage('Static Analysis') {
      steps {
        script {
          def scannerHome = tool 'sonar-scanner4.5'
          withSonarQubeEnv () {
            sh """
              ${scannerHome}/bin/sonar-scanner
                -Dsonar.host.url=http://sonarqube:9000
                -Dsonar.login=admin
                -Dsonar.password=admin
                -Dsonar.projectKey=someapp-${env.BRANCH_NAME}
                -Dsonar.projectName=someapp-${env.BRANCH_NAME}
                -Dsonar.projectVersion=${env.PROJ_VERSION}
                -Dsonar.language=java
                -Dsonar.sources=src/main/java
                -Dsonar.sourceEncoding=UTF-8
                -Dsonar.tests=src/test/java
                -Dsonar.java.binaries=**/target/classes
                -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/**/*
            """
          }
          timeout(time: 1, unit: 'HOURS') {
            waitForQualityGate abortPipeline: true
          }
        }
      }
      post{
        always {
          echo 'static analysis complete'
        }
      }
    }
  }
}
```

**Jenkins Settings:**
_**Plugin:**_ SonarQube Scanner for Jenkins v2.12
_**SonarQube Scanner:**_ v.4.5.0.2216

**System Configuration:**
![jenkins-configure-ss](https://user-images.githubusercontent.com/72370355/99999750-84ca1280-2db8-11eb-9df2-6a531a414b30.png)

**Tool Configuration:**
![jenkins-configure-tools-ss](https://user-images.githubusercontent.com/72370355/100000002-e4282280-2db8-11eb-81f6-4b9cd669f10e.png)

**Environment:**
I am running sonarqube container + postgres container + jenkins container
sonarqube version: 8.5.1-community
postgres version: 12-alpine
jenkins version: jenkins/jenkins

**Docker Compose File:**
```
version: "3.8"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile_jenkins
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    networks:
      - host_frontend
    deploy:
      mode: global
    ports:
      - 8091:8080
      - 50000:50000

  sonarqube:
    build:
      context: .
      dockerfile: Dockerfile_sonarqube
    container_name: sonarqube
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_ext:/opt/sonarqube/extensions
      - sonarqube_plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - host_frontend
      - sonar_net
    deploy:
      mode: global
    restart: on-failure
    ports:
      - 9000:9000
    depends_on:
      - postgres

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    shm_size: 256M
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sonar_net
    deploy:
      mode: global
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  jenkins_home:
    external: true
  sonarqube_data: {}
  sonarqube_logs: {}
  sonarqube_ext: {}
  sonarqube_plugins: {}
  pgdata: {}

networks:
  host_frontend: {}
  sonar_net: {}
```
**Other notes**
A similar behavior is observed for the parameter sonar.java.binaries as well.

**Workaround:**
create the sonar-project.properties file containing at least the following keys:
sonar.projectKey=someapp
sonar.java.binaries=target/classes

**Comment by lcabahug** [comment]
This was a duplicate of #448 . I added the backslashes on each line in my scanner arguments and it's now working fine. Thank You.
