### ISSUE TITLE
Issue while deploying sonarqube on Openshift - Failed to reset file system

### ISSUE THREAD

**Issue by naveenk232** [SonarSource/docker-sonarqube#46]
Hello ,

Please help -  I am trying to deploy sonarqube on OpenShift using docker file , Build is working , after deployment , I am seeing error.

2016.08.31 07:37:32 INFO  app[o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
Exception in thread "main" java.lang.RuntimeException: Failed to reset file system
	at org.sonar.process.monitor.Monitor.resetFileSystem(Monitor.java:127)
	at org.sonar.process.monitor.Monitor.startProcesses(Monitor.java:107)
	at org.sonar.process.monitor.Monitor.start(Monitor.java:101)
	at org.sonar.application.App.start(App.java:54)
	at org.sonar.application.App.main(App.java:141)
Caused by: java.nio.file.AccessDeniedException: /opt/sonarqube/temp/README.txt
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:244)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at org.sonar.application.AppFileSystem$CleanTempDirFileVisitor.visitFile(AppFileSystem.java:149)
	at org.sonar.application.AppFileSystem$CleanTempDirFileVisitor.visitFile(AppFileSystem.java:130)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at org.sonar.application.AppFileSystem.createOrCleanTempDirectory(AppFileSystem.java:126)
	at org.sonar.application.AppFileSystem.reset(AppFileSystem.java:83)
	at org.sonar.process.monitor.Monitor.resetFileSystem(Monitor.java:124)
	... 4 more

```
RUN set -x \
   && yum -y install tar unzip \
    && yum -y update \
    && yum -y clean all 
    
    
#java
ENV JAVA_HOME /opt/java
ENV JAVA_VERSION_MAJOR 8
ENV JAVA_VERSION_MINOR 102
ENV JAVA_VERSION_BUILD 14

RUN mkdir -p /opt \
  && curl --fail --silent --location --retry 3 \
  --header "Cookie: oraclelicense=accept-securebackup-cookie; " \
  http://download.oracle.com/otn-pub/java/jdk/${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-b${JAVA_VERSION_BUILD}/server-jre-${JAVA_VERSION_MAJOR}u${JAVA_VERSION_MINOR}-linux-x64.tar.gz \
  | gunzip \
  | tar -x -C /opt \
  && ln -s /opt/jdk1.${JAVA_VERSION_MAJOR}.0_${JAVA_VERSION_MINOR} ${JAVA_HOME}

    
    
ENV SONAR_VERSION=6.0 \
    SONARQUBE_HOME=/opt/sonarqube \
    # Database configuration
    # Defaults to using H2
    SONARQUBE_JDBC_USERNAME=sonar \
    SONARQUBE_JDBC_PASSWORD=sonar \
    SONARQUBE_JDBC_URL=

# Http port
EXPOSE 9000

 RUN set -x \

    # see https://bugs.debian.org/812708
    # and https://github.com/SonarSource/docker-sonarqube/pull/18#issuecomment-194045499
    && cd /tmp \
#    && curl -fSL -O "https://archive.raspbian.org/raspbian/pool/main/c/ca-certificates/ca-certificates_20130119+deb7u1_all.deb" \
#    && echo "3494ecfd607e4233d8d1a656eceb6bd109d756bc0afe9d3b29dfc0acc4fe19cf  ca-certificates_20130119+deb7u1_all.deb" | sha256sum -c - \
#    && dpkg -P --force-all ca-certificates \
#    && dpkg -i ca-certificates_20130119+deb7u1_all.deb \
#    && rm ca-certificates_20130119+deb7u1_all.deb \

    # pub   2048R/D26468DE 2015-05-25
    #       Key fingerprint = F118 2E81 C792 9289 21DB  CAB4 CFCA 4A29 D264 68DE
    # uid                  sonarsource_deployer (Sonarsource Deployer) <infra@sonarsource.com>
    # sub   2048R/06855C1D 2015-05-25
   # && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys F1182E81C792928921DBCAB4CFCA4A29D26468DE \

    && cd /opt \
    && curl -o sonarqube.zip -fSL https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-$SONAR_VERSION.zip \
 #   && curl -o sonarqube.zip.asc -fSL https://sonarsource.bintray.com/Distribution/sonarqube/sonarqube-$SONAR_VERSION.zip.asc \
 #   && gpg --batch --verify sonarqube.zip.asc sonarqube.zip \
    && unzip sonarqube.zip \
    && mv sonarqube-$SONAR_VERSION sonarqube \
    && rm sonarqube.zip* \
    && rm -rf $SONARQUBE_HOME/bin/*

VOLUME ["$SONARQUBE_HOME/data", "$SONARQUBE_HOME/extensions"]

WORKDIR $SONARQUBE_HOME
COPY containerfiles/run.sh $SONARQUBE_HOME/bin/
RUN chmod a+x $SONARQUBE_HOME/bin/run.sh
ENTRYPOINT ["./bin/run.sh"]
```

Regards
Naveen

**Comment by Godin** [comment]
@naveenk232 IMO exception message is easy to interpret:
> Caused by: java.nio.file.AccessDeniedException: /opt/sonarqube/temp/README.txt

Check permissions, which are set for user and files. SonarQube requires write access to some directories of its installation.
