### ISSUE TITLE
As a sonarqube noob, I just hit the following- 

### ISSUE THREAD

**Issue by topiaruss** [SonarSource/docker-sonarqube#48]
docker 1.12.1
OSX

```
$ docker run -it --name sonarqube -p 9000:9000 -p 9092:9092 sonarqube
2016.09.30 10:22:09 INFO  app[o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2016.09.30 10:22:09 INFO  app[o.s.p.m.JavaProcessLauncher] Launch process[es]: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Xmx1G -Xms256m -Xss256k -Djna.nosys=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=/opt/sonarqube/temp -javaagent:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/management-agent.jar -cp ./lib/common/*:./lib/search/* org.sonar.search.SearchServer /opt/sonarqube/temp/sq-process6442907441851531919properties
2016.09.30 10:22:10 INFO   es[o.s.p.ProcessEntryPoint]  Starting es
2016.09.30 10:22:10 INFO   es[o.s.s.EsSettings]  Elasticsearch listening on /127.0.0.1:9001
2016.09.30 10:22:10 INFO   es[o.elasticsearch.node]  [sonar-1475230929584] version[2.3.3], pid[22], build[218bdf1/2016-05-17T15:40:04Z]
2016.09.30 10:22:10 INFO   es[o.elasticsearch.node]  [sonar-1475230929584] initializing ...
2016.09.30 10:22:10 INFO   es[o.e.plugins]  [sonar-1475230929584] modules [], plugins [], sites []
2016.09.30 10:22:10 INFO   es[o.elasticsearch.env]  [sonar-1475230929584] using [1] data paths, mounts [[/opt/sonarqube/data (/dev/vda1)]], net usable_space [4.5gb], net total_space [17.8gb], spins? [possibly], types [ext4]
2016.09.30 10:22:10 INFO   es[o.elasticsearch.env]  [sonar-1475230929584] heap size [990.7mb], compressed ordinary object pointers [true]
2016.09.30 10:23:16 INFO   es[o.elasticsearch.node]  [sonar-1475230929584] initialized
2016.09.30 10:23:16 INFO   es[o.elasticsearch.node]  [sonar-1475230929584] starting ...
2016.09.30 10:23:16 INFO   es[o.e.transport]  [sonar-1475230929584] publish_address {127.0.0.1:9001}, bound_addresses {127.0.0.1:9001}
2016.09.30 10:23:16 INFO   es[o.e.discovery]  [sonar-1475230929584] sonarqube/p74qeoA3SSOVQO0Whuy-OQ
2016.09.30 10:24:05 WARN   es[o.e.discovery]  [sonar-1475230929584] waited for 30s and no initial state was set by the discovery
2016.09.30 10:24:05 INFO   es[o.elasticsearch.node]  [sonar-1475230929584] started
2016.09.30 10:24:05 INFO   es[o.e.cluster.service]  [sonar-1475230929584] new_master {sonar-1475230929584}{p74qeoA3SSOVQO0Whuy-OQ}{127.0.0.1}{127.0.0.1:9001}{rack_id=sonar-1475230929584}, reason: zen-disco-join(elected_as_master, [0] joins received)
2016.09.30 10:24:05 INFO   es[o.e.gateway]  [sonar-1475230929584] recovered [0] indices into cluster_state
2016.09.30 10:24:05 INFO  app[o.s.p.m.Monitor] Process[es] is up
2016.09.30 10:24:05 INFO  app[o.s.p.m.JavaProcessLauncher] Launch process[web]: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djruby.management.enabled=false -Djruby.compile.invokedynamic=false -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Djava.io.tmpdir=/opt/sonarqube/temp -javaagent:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/management-agent.jar -cp ./lib/common/*:./lib/server/*:/opt/sonarqube/lib/jdbc/h2/h2-1.3.176.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process9041180091653102695properties
2016.09.30 10:24:06 INFO  web[o.s.p.ProcessEntryPoint] Starting web
2016.09.30 10:24:06 INFO  web[o.s.s.a.TomcatContexts] Webapp directory: /opt/sonarqube/web
2016.09.30 10:24:07 INFO  web[o.a.c.h.Http11NioProtocol] Initializing ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.09.30 10:24:07 INFO  web[o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
2016.09.30 10:24:07 INFO  web[o.s.s.p.ServerImpl] SonarQube Server / 6.0 / 93442889cd219e78b028c7dcf51a30de74c987fe
2016.09.30 10:24:08 INFO  web[o.s.s.d.EmbeddedDatabase] Starting embedded database on port 9092 with url jdbc:h2:tcp://localhost:9092/sonar
2016.09.30 10:24:08 INFO  web[o.s.s.d.EmbeddedDatabase] Embedded database started. Data stored in: /opt/sonarqube/data
2016.09.30 10:24:08 INFO  web[o.sonar.db.Database] Create JDBC data source for jdbc:h2:tcp://localhost:9092/sonar
2016.09.30 10:24:08 WARN  web[o.s.d.DatabaseChecker] H2 database should be used for evaluation purpose only
2016.09.30 10:24:09 INFO  web[o.s.s.p.DefaultServerFileSystem] SonarQube home: /opt/sonarqube
2016.09.30 10:24:09 INFO  web[o.e.plugins] [sonar-1475230929584] modules [], plugins [], sites []
2016.09.30 10:25:14 INFO  web[o.s.s.p.ServerPluginRepository] Plugin C# [csharp] installed
2016.09.30 10:25:14 INFO  web[o.s.s.p.ServerPluginRepository] Plugin JavaScript [javascript] installed
2016.09.30 10:25:14 INFO  web[o.s.s.p.ServerPluginRepository] Plugin Git [scmgit] installed
2016.09.30 10:25:14 INFO  web[o.s.s.p.ServerPluginRepository] Plugin Java [java] installed
2016.09.30 10:25:14 INFO  web[o.s.s.p.ServerPluginRepository] Plugin SVN [scmsvn] installed
2016.09.30 10:25:14 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin C# / 5.3.1 / 829e9f5ce2582c2e45f2db2130d2fbaa509fbc64
2016.09.30 10:25:14 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin Git / 1.2 / a713dd64daf8719ba4e7f551f9a1966c62690c17
2016.09.30 10:25:14 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin Java / 4.0 / b653c6c8640ab3d6015d036a060f58e027a653af
2016.09.30 10:25:14 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin JavaScript / 2.14 / 8e37a262d72dd863345f9c6e87421e2d1853a2e6
2016.09.30 10:25:14 INFO  web[o.s.s.p.ServerPluginRepository] Deploy plugin SVN / 1.3 / aff503d48bc77b07c2b62abf93249d0a20bd355c
2016.09.30 10:25:15 INFO  web[o.s.s.d.m.DatabaseMigrator] Create database
2016.09.30 10:25:15 INFO  web[o.s.s.p.RailsAppsDeployer] Deploying Ruby on Rails applications
2016.09.30 10:25:16 INFO  web[o.s.s.p.UpdateCenterClient] Update center: http://update.sonarsource.org/update-center.properties (no proxy)
2016.09.30 10:25:17 INFO  web[o.s.s.e.IndexCreator] Create index tests
2016.09.30 10:25:17 INFO   es[o.e.cluster.metadata]  [sonar-1475230929584] [tests] creating index, cause [api], templates [], shards [5]/[0], mappings []
2016.09.30 10:25:24 INFO  web[o.e.client.transport] [sonar-1475230929584] failed to get node info for {#transport#-1}{127.0.0.1}{127.0.0.1:9001}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:9001][cluster:monitor/nodes/liveness] request_id [3] timed out after [5001ms]
       	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
       	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016.09.30 10:25:34 INFO  web[o.e.client.transport] [sonar-1475230929584] failed to get node info for {#transport#-1}{127.0.0.1}{127.0.0.1:9001}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:9001][cluster:monitor/nodes/liveness] request_id [4] timed out after [5000ms]
       	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
       	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016.09.30 10:25:44 INFO  web[o.e.client.transport] [sonar-1475230929584] failed to get node info for {#transport#-1}{127.0.0.1}{127.0.0.1:9001}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:9001][cluster:monitor/nodes/liveness] request_id [5] timed out after [5000ms]
       	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
       	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016.09.30 10:25:54 INFO  web[o.e.client.transport] [sonar-1475230929584] failed to get node info for {#transport#-1}{127.0.0.1}{127.0.0.1:9001}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:9001][cluster:monitor/nodes/liveness] request_id [6] timed out after [5000ms]
       	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
       	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016.09.30 10:26:04 INFO  web[o.e.client.transport] [sonar-1475230929584] failed to get node info for {#transport#-1}{127.0.0.1}{127.0.0.1:9001}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:9001][cluster:monitor/nodes/liveness] request_id [7] timed out after [5001ms]
       	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
       	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016.09.30 10:26:14 INFO  web[o.e.client.transport] [sonar-1475230929584] failed to get node info for {#transport#-1}{127.0.0.1}{127.0.0.1:9001}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:9001][cluster:monitor/nodes/liveness] request_id [8] timed out after [5000ms]
       	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
       	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016.09.30 10:26:22 WARN   es[o.e.cluster.service]  [sonar-1475230929584] cluster state update task [create-index [tests], cause [api]] took 1m above the warn threshold of 30s
2016.09.30 10:26:32 INFO  web[o.e.client.transport] [sonar-1475230929584] failed to get node info for {#transport#-1}{127.0.0.1}{127.0.0.1:9001}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:9001][cluster:monitor/nodes/liveness] request_id [10] timed out after [5001ms]
       	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
       	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016.09.30 10:26:42 INFO  web[o.e.client.transport] [sonar-1475230929584] failed to get node info for {#transport#-1}{127.0.0.1}{127.0.0.1:9001}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:9001][cluster:monitor/nodes/liveness] request_id [11] timed out after [5000ms]
       	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
       	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016.09.30 10:26:52 INFO  web[o.e.client.transport] [sonar-1475230929584] failed to get node info for {#transport#-1}{127.0.0.1}{127.0.0.1:9001}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:9001][cluster:monitor/nodes/liveness] request_id [12] timed out after [5001ms]
       	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
       	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016.09.30 10:27:02 INFO  web[o.e.client.transport] [sonar-1475230929584] failed to get node info for {#transport#-1}{127.0.0.1}{127.0.0.1:9001}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:9001][cluster:monitor/nodes/liveness] request_id [13] timed out after [5000ms]
       	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
       	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016.09.30 10:27:12 INFO  web[o.e.client.transport] [sonar-1475230929584] failed to get node info for {#transport#-1}{127.0.0.1}{127.0.0.1:9001}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:9001][cluster:monitor/nodes/liveness] request_id [14] timed out after [5000ms]
       	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
       	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016.09.30 10:27:22 INFO  web[o.e.client.transport] [sonar-1475230929584] failed to get node info for {#transport#-1}{127.0.0.1}{127.0.0.1:9001}, disconnecting...
org.elasticsearch.transport.ReceiveTimeoutTransportException: [][127.0.0.1:9001][cluster:monitor/nodes/liveness] request_id [15] timed out after [5000ms]
       	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
       	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016.09.30 10:27:26 INFO  web[o.s.s.d.EmbeddedDatabase] Embedded database stopped
2016.09.30 10:27:26 ERROR web[o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{127.0.0.1:9001}]
       	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:853) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:86) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:56) ~[elasticsearch-2.3.3.jar:2.3.3]
       	at org.sonar.server.es.request.ProxyClusterHealthRequestBuilder.get(ProxyClusterHealthRequestBuilder.java:42) ~[sonar-server-6.0.jar:na]
       	at org.sonar.server.es.request.ProxyClusterHealthRequestBuilder.get(ProxyClusterHealthRequestBuilder.java:32) ~[sonar-server-6.0.jar:na]
       	at org.sonar.server.es.EsClient.waitForStatus(EsClient.java:130) ~[sonar-server-6.0.jar:na]
       	at org.sonar.server.es.IndexCreator.createIndex(IndexCreator.java:88) ~[sonar-server-6.0.jar:na]
       	at org.sonar.server.es.IndexCreator.start(IndexCreator.java:66) ~[sonar-server-6.0.jar:na]
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
       	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
       	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110) ~[picocontainer-2.15.jar:na]
       	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89) ~[picocontainer-2.15.jar:na]
       	at org.sonar.core.platform.ComponentContainer$1.start(ComponentContainer.java:320) ~[sonar-core-6.0.jar:na]
       	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84) ~[picocontainer-2.15.jar:na]
       	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169) ~[picocontainer-2.15.jar:na]
       	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132) ~[picocontainer-2.15.jar:na]
       	at org.picocontainer.behaviors.Stored.start(Stored.java:110) ~[picocontainer-2.15.jar:na]
       	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016) ~[picocontainer-2.15.jar:na]
       	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009) ~[picocontainer-2.15.jar:na]
       	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767) ~[picocontainer-2.15.jar:na]
       	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:141) ~[sonar-core-6.0.jar:na]
       	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:84) ~[sonar-server-6.0.jar:na]
       	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:687) ~[sonar-server-6.0.jar:na]
       	at org.sonar.server.platform.Platform.start(Platform.java:216) ~[sonar-server-6.0.jar:na]
       	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:190) ~[sonar-server-6.0.jar:na]
       	at org.sonar.server.platform.Platform.doStart(Platform.java:113) ~[sonar-server-6.0.jar:na]
       	at org.sonar.server.platform.Platform.doStart(Platform.java:99) ~[sonar-server-6.0.jar:na]
       	at org.sonar.server.platform.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:44) ~[sonar-server-6.0.jar:na]
       	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812) [tomcat-embed-core-8.0.32.jar:8.0.32]
       	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255) [tomcat-embed-core-8.0.32.jar:8.0.32]
       	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [tomcat-embed-core-8.0.32.jar:8.0.32]
       	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408) [tomcat-embed-core-8.0.32.jar:8.0.32]
       	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398) [tomcat-embed-core-8.0.32.jar:8.0.32]
       	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_102]
       	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_102]
       	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_102]
       	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_102]
2016.09.30 10:27:26 ERROR web[o.a.c.c.StandardContext] One or more listeners failed to start. Full details will be found in the appropriate container log file
2016.09.30 10:27:26 ERROR web[o.a.c.c.StandardContext] Context [] startup failed due to previous errors
2016.09.30 10:27:26 INFO  web[o.a.c.h.Http11NioProtocol] Starting ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.09.30 10:27:26 INFO  web[o.s.s.a.TomcatAccessLog] Web server is started
2016.09.30 10:27:26 INFO  web[o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2016.09.30 10:27:26 WARN  web[o.s.p.ProcessEntryPoint] Fail to start web
java.lang.IllegalStateException: Webapp did not start
       	at org.sonar.server.app.EmbeddedTomcat.isUp(EmbeddedTomcat.java:84) ~[sonar-server-6.0.jar:na]
       	at org.sonar.server.app.WebServer.isUp(WebServer.java:47) [sonar-server-6.0.jar:na]
       	at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:105) ~[sonar-process-6.0.jar:na]
       	at org.sonar.server.app.WebServer.main(WebServer.java:68) [sonar-server-6.0.jar:na]
2016.09.30 10:27:26 INFO  web[o.a.c.h.Http11NioProtocol] Pausing ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.09.30 10:27:26 INFO  web[o.a.c.h.Http11NioProtocol] Stopping ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.09.30 10:27:26 INFO  web[o.a.c.h.Http11NioProtocol] Destroying ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.09.30 10:27:26 INFO  web[o.s.s.a.TomcatAccessLog] Web server is stopped
2016.09.30 10:27:26 INFO   es[o.e.c.r.allocation]  [sonar-1475230929584] Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[tests][4]] ...]).
2016.09.30 10:28:29 INFO  app[o.s.p.m.Monitor] Process[es] is stopping
2016.09.30 10:28:29 INFO   es[o.s.p.StopWatcher]  Stopping process
2016.09.30 10:28:29 INFO   es[o.elasticsearch.node]  [sonar-1475230929584] stopping ...
2016.09.30 10:28:29 INFO   es[o.elasticsearch.node]  [sonar-1475230929584] stopped
2016.09.30 10:28:29 INFO   es[o.elasticsearch.node]  [sonar-1475230929584] closing ...
2016.09.30 10:28:29 INFO   es[o.elasticsearch.node]  [sonar-1475230929584] closed
2016.09.30 10:28:30 INFO  app[o.s.p.m.Monitor] Process[es] is stopped

```

**Comment by Godin** [comment]
Cannot reproduce. 

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G1004

$ docker --version
Docker version 1.12.1, build 6f9534c

$ docker images sonarqube
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
sonarqube           latest              b81c88bdf1fc        6 days ago          785.6 MB
```

Maybe CPU of your machine is under pressure caused by other processes, causing timeouts for Elasticsearch used by SonarQube.

**Comment by topiaruss** [comment]
Thanks. Yes. I had cassandra running. 16GB only goes so far.
