### ISSUE TITLE
Cannot update plugins when using docker-compose

### ISSUE THREAD

**Issue by LorenzoBettini** [SonarSource/docker-sonarqube#55]
I run Sonarqube using docker-compose and the recipe https://github.com/SonarSource/docker-sonarqube/blob/master/recipes.md

When I login and check for updates, no update shows, and in the console I see this error (note that in my host I can access https://update.sonarsource.org/update-center.properties):

```
sonarqube_1  | 2016.12.02 11:57:11 ERROR web[][o.s.s.p.UpdateCenterClient] Fail to connect to update center
sonarqube_1  | org.sonar.api.utils.SonarException: Fail to download: https://update.sonarsource.org/update-center.properties (no proxy)
sonarqube_1  | 	at org.sonar.core.util.DefaultHttpDownloader.failToDownload(DefaultHttpDownloader.java:157) ~[sonar-core-6.1.jar:na]
sonarqube_1  | 	at org.sonar.core.util.DefaultHttpDownloader.readString(DefaultHttpDownloader.java:115) ~[sonar-core-6.1.jar:na]
sonarqube_1  | 	at org.sonar.api.utils.UriReader.readString(UriReader.java:72) ~[sonar-plugin-api-6.1.jar:na]
sonarqube_1  | 	at org.sonar.server.plugins.UpdateCenterClient.init(UpdateCenterClient.java:109) [sonar-server-6.1.jar:na]
sonarqube_1  | 	at org.sonar.server.plugins.UpdateCenterClient.getUpdateCenter(UpdateCenterClient.java:92) [sonar-server-6.1.jar:na]
sonarqube_1  | 	at org.sonar.server.plugins.UpdateCenterMatrixFactory.getUpdateCenter(UpdateCenterMatrixFactory.java:44) [sonar-server-6.1.jar:na]
sonarqube_1  | 	at org.sonar.server.plugins.ws.PluginWSCommons.compatiblePlugins(PluginWSCommons.java:277) [sonar-server-6.1.jar:na]
sonarqube_1  | 	at org.sonar.server.plugins.ws.PluginWSCommons.compatiblePluginsByKey(PluginWSCommons.java:282) [sonar-server-6.1.jar:na]
sonarqube_1  | 	at org.sonar.server.plugins.ws.PendingAction.handle(PendingAction.java:85) [sonar-server-6.1.jar:na]
sonarqube_1  | 	at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:109) [sonar-server-6.1.jar:na]
sonarqube_1  | 	at org.sonar.server.ws.WebServiceFilter.doFilter(WebServiceFilter.java:74) [sonar-server-6.1.jar:na]
sonarqube_1  | 	at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:126) [sonar-server-6.1.jar:na]
sonarqube_1  | 	at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:95) [sonar-server-6.1.jar:na]
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:60) [sonar-server-6.1.jar:na]
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at org.sonar.server.platform.web.RoutesFilter.doFilter(RoutesFilter.java:55) [sonar-server-6.1.jar:na]
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:113) [sonar-server-6.1.jar:na]
sonarqube_1  | 	at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:81) [sonar-server-6.1.jar:na]
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:191) [logback-access-1.1.3.jar:na]
sonarqube_1  | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
sonarqube_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
sonarqube_1  | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.0.32.jar:8.0.32]
sonarqube_1  | 	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
sonarqube_1  | Caused by: java.net.UnknownHostException: update.sonarsource.org
sonarqube_1  | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_111]
sonarqube_1  | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_111]
sonarqube_1  | 	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_111]
sonarqube_1  | 	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668) ~[na:1.8.0_111]
sonarqube_1  | 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_111]
sonarqube_1  | 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[na:1.8.0_111]
sonarqube_1  | 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[na:1.8.0_111]
sonarqube_1  | 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264) ~[na:1.8.0_111]
sonarqube_1  | 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367) ~[na:1.8.0_111]
sonarqube_1  | 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191) ~[na:1.8.0_111]
sonarqube_1  | 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138) ~[na:1.8.0_111]
sonarqube_1  | 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032) ~[na:1.8.0_111]
sonarqube_1  | 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177) ~[na:1.8.0_111]
sonarqube_1  | 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:153) ~[na:1.8.0_111]
sonarqube_1  | 	at org.sonar.core.util.DefaultHttpDownloader$BaseHttpDownloader$HttpInputSupplier.getInput(DefaultHttpDownloader.java:305) ~[sonar-core-6.1.jar:na]
sonarqube_1  | 	at org.sonar.core.util.DefaultHttpDownloader.readString(DefaultHttpDownloader.java:113) ~[sonar-core-6.1.jar:na]
sonarqube_1  | 	... 38 common frames omitted
```

**Comment by LorenzoBettini** [comment]
Looks like I've hit by https://github.com/docker/docker/issues/23910 so this has nothing to do with sonarqube e compose

**Comment by Godin** [comment]
@LorenzoBettini glad that you found root cause and thanks for notification!
