### ISSUE TITLE
sonarqube failed to connect to database mysql

### ISSUE THREAD

**Issue by vibgyorvip** [SonarSource/docker-sonarqube#563]
I'm trying to run a sonarqube  with MySQL installed running on the same  machine !

while running "./sonar.sh start" command giving below error:-

# web.log

2022.08.04 23:57:17 INFO  web[][o.s.p.ProcessEntryPoint] Starting web
2022.08.04 23:57:18 INFO  web[][o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
2022.08.04 23:57:19 INFO  web[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [http://localhost:9001]
2022.08.04 23:57:19 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 8.9.9.56886 / f7ef403a1f66dde923eda25b58df08d40a16e043
2022.08.04 23:57:19 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:sqlserver://localhost:3306/sonar?useUnicode=true&amp;characterEncoding=utf8
2022.08.04 23:57:19 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed
java.lang.IllegalStateException: Fail to connect to database
        at org.sonar.db.DefaultDatabase.start(DefaultDatabase.java:86)
        at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
        at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
        at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
        at org.picocontainer.behaviors.Stored.start(Stored.java:110)
        at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
        at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
        at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
        at org.sonar.server.platform.platformlevel.PlatformLevel1.start(PlatformLevel1.java:166)
        at org.sonar.server.platform.PlatformImpl.start(PlatformImpl.java:213)
        at org.sonar.server.platform.PlatformImpl.startLevel1Container(PlatformImpl.java:172)
        at org.sonar.server.platform.PlatformImpl.init(PlatformImpl.java:86)
        at org.sonar.server.platform.web.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:43)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4763)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5232)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1429)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Can not connect to database. Please check connectivity and settings (see the properties prefixed by 'sonar.jdbc.').
        at org.sonar.db.DefaultDatabase.checkConnection(DefaultDatabase.java:118)
        at org.sonar.db.DefaultDatabase.start(DefaultDatabase.java:83)
        ... 24 common frames omitted
Caused by: java.sql.SQLException: Cannot create PoolableConnectionFactory (The port number 3306/sonar?useUnicode=true&amp is not valid.)
        at org.apache.commons.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:669)
        at org.apache.commons.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:544)
        at org.apache.commons.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753)
        at org.sonar.db.profiling.NullConnectionInterceptor.getConnection(NullConnectionInterceptor.java:31)
        at org.sonar.db.profiling.ProfiledDataSource.getConnection(ProfiledDataSource.java:317)

# sonar.20220804.log 
--> Wrapper Started as Daemon
Launching a JVM...
Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
  Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.

2022.08.04 23:57:04 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2022.08.04 23:57:04 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on [HTTP: 127.0.0.1:9001, TCP: 127.0.0.1:39254]
2022.08.04 23:57:04 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch
2022.08.04 23:57:04 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
warning: no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
2022.08.04 23:57:17 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2022.08.04 23:57:17 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonarqube]: /usr/lib/jvm/java-11-openjdk-11.0.16.0.8-1.el7_9.x86_64/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Dhttp.proxyHost=proxy-wsa.esl.cisco.com -Dhttp.proxyPort=80 -Dhttp.nonProxyHosts=localhost|127.*|[::1] -Dhttps.proxyHost=proxy-wsa.esl.cisco.com -Dhttps.proxyPort=80 -cp ./lib/sonar-application-8.9.9.56886.jar:/opt/sonarqube/lib/jdbc/mssql/mssql-jdbc-9.2.0.jre11.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process4259927929457193829properties
~

# Attaching sonar.properties file
#----- Default Sonar server
sonar.host.url=http://xx.xx.xx.xx:9000
sonar.jdbc.username=root
sonar.jdbc.password=xxxxxx
#sonar.jdbc.url=jdbc:sqlserver://localhost;databaseName=sonar
sonar.jdbc.url=jdbc:sqlserver://localhost:3306/sonar?useUnicode=true&amp;characterEncoding=utf8
sonar.jdbc.driver=com.sqlserver.jdbc.Driver
sonar.jdbc.maxActive=20
sonar.jdbc.maxIdle=5
sonar.jdbc.minIdle=2
sonar.jdbc.maxWait=5000
sonar.jdbc.minEvictableIdleTimeMillis=600000
sonar.jdbc.timeBetweenEvictionRunsMillis=30000
vm.max_map_count=262144
sonar.search.javaOpts=-Xmx512m -Xms512m -XX:MaxDirectMemorySize=256m -XX:+HeapDumpOnOutOfMemoryError

Please help Here !

 #221

**Comment by nixel2007** [comment]
MySQL support was dropped in v7.9

**Comment by vibgyorvip** [comment]
Thanks @nixel2007 for your help.

**Comment by vibgyorvip** [comment]
Uninstalled MySQL ,installed the PostgreSQL database and able to connect from sonarqube successfully . Now sonarqube is up and running on port 9000 but not able to access through browser .
Also not able to see any error .

**Comment by jCOTINEAU** [comment]
hello @vibgyorvip , thanks a lot for taking the time to participate in the community.

Regarding that your issue seems to not be related to Docker image but running SonarQube locally, i would suggest to fill an issue on the community if it still relevant [here](https://community.sonarsource.com/)

Else i am closing the issue, do not hesitate to reopen it.
