### ISSUE TITLE
Crash at container start

### ISSUE THREAD

**Issue by blackfinn** [SonarSource/docker-sonarqube#57]
Hi, I've pulled an sonarcube image with:
`docker pull sonarqube:5.6.3`
If I try to run a container based on that image (as described) with:
`docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 -e SONARQUBE_JDBC_USERNAME=sonar -e SONARQUBE_JDBC_PASSWORD=sonar -e SONARQUBE_JDBC_URL=jdbc:postgresql://localhost/sonar sonarqube:5.6.3`
the container always "crashes" with the following log:

```
2016.12.04 14:14:20 INFO  app[o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2016.12.04 14:14:20 INFO  app[o.s.p.m.JavaProcessLauncher] Launch process[es]: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Xmx1G -Xms256m -Xss256k -Djava.net.preferIPv4Stack=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=/opt/sonarqube/temp -javaagent:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/management-agent.jar -cp ./lib/common/*:./lib/search/* org.sonar.search.SearchServer /opt/sonarqube/temp/sq-process4183878926937211717properties
2016.12.04 14:14:20 INFO   es[o.s.p.ProcessEntryPoint]  Starting es
2016.12.04 14:14:20 INFO   es[o.s.s.EsSettings]  Elasticsearch listening on 127.0.0.1:9001
2016.12.04 14:14:20 INFO   es[o.elasticsearch.node]  [sonar-1480860860022] version[1.7.5], pid[20], build[00f95f4/2016-02-02T09:55:30Z]
2016.12.04 14:14:20 INFO   es[o.elasticsearch.node]  [sonar-1480860860022] initializing ...
2016.12.04 14:14:20 INFO   es[o.e.plugins]  [sonar-1480860860022] loaded [], sites []
2016.12.04 14:14:20 INFO   es[o.elasticsearch.env]  [sonar-1480860860022] using [1] data paths, mounts [[/opt/sonarqube/data (/dev/sda1)]], net usable_space [82.6gb], net total_space [94.3gb], types [ext4]
2016.12.04 14:14:21 WARN   es[o.e.bootstrap]  JNA not found. native methods will be disabled.
2016.12.04 14:14:22 INFO   es[o.elasticsearch.node]  [sonar-1480860860022] initialized
2016.12.04 14:14:22 INFO   es[o.elasticsearch.node]  [sonar-1480860860022] starting ...
2016.12.04 14:14:22 INFO   es[o.e.transport]  [sonar-1480860860022] bound_address {inet[/127.0.0.1:9001]}, publish_address {inet[/127.0.0.1:9001]}
2016.12.04 14:14:22 INFO   es[o.e.discovery]  [sonar-1480860860022] sonarqube/383RrHruQXKC9Jd8TVqu0g
2016.12.04 14:14:25 INFO   es[o.e.cluster.service]  [sonar-1480860860022] new_master [sonar-1480860860022][383RrHruQXKC9Jd8TVqu0g][7633006c8b2d][inet[/127.0.0.1:9001]]{rack_id=sonar-1480860860022}, reason: zen-disco-join (elected_as_master)
2016.12.04 14:14:25 INFO   es[o.elasticsearch.node]  [sonar-1480860860022] started
2016.12.04 14:14:25 INFO   es[o.e.gateway]  [sonar-1480860860022] recovered [0] indices into cluster_state
2016.12.04 14:14:25 INFO  app[o.s.p.m.Monitor] Process[es] is up
2016.12.04 14:14:25 INFO  app[o.s.p.m.JavaProcessLauncher] Launch process[web]: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djruby.management.enabled=false -Djruby.compile.invokedynamic=false -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:/dev/./urandom -Djava.io.tmpdir=/opt/sonarqube/temp -javaagent:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/management-agent.jar -cp ./lib/common/*:./lib/server/*:/opt/sonarqube/lib/jdbc/postgresql/postgresql-9.3-1102-jdbc41.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process1441227969328238100properties
2016.12.04 14:14:26 INFO  web[o.s.p.ProcessEntryPoint] Starting web
2016.12.04 14:14:26 INFO  web[o.s.s.a.TomcatContexts] Webapp directory: /opt/sonarqube/web
2016.12.04 14:14:26 INFO  web[o.a.c.h.Http11NioProtocol] Initializing ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.12.04 14:14:26 INFO  web[o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
2016.12.04 14:14:26 INFO  web[o.s.s.p.ServerImpl] SonarQube Server / 5.6.3 / 3fcc98a73d6afb99388e39f46272909a6d6600b2
2016.12.04 14:14:26 INFO  web[o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://localhost/sonar
2016.12.04 14:14:26 ERROR web[o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
java.lang.IllegalStateException: Can not connect to database. Please check connectivity and settings (see the properties prefixed by 'sonar.jdbc.').
	at org.sonar.db.DefaultDatabase.checkConnection(DefaultDatabase.java:104) ~[sonar-db-5.6.3.jar:na]
	at org.sonar.db.DefaultDatabase.start(DefaultDatabase.java:71) ~[sonar-db-5.6.3.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111]
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89) ~[picocontainer-2.15.jar:na]
	at org.sonar.core.platform.ComponentContainer$1.start(ComponentContainer.java:320) ~[sonar-core-5.6.3.jar:na]
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.behaviors.Stored.start(Stored.java:110) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767) ~[picocontainer-2.15.jar:na]
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:141) ~[sonar-core-5.6.3.jar:na]
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:84) ~[sonar-server-5.6.3.jar:na]
	at org.sonar.server.platform.Platform.start(Platform.java:216) ~[sonar-server-5.6.3.jar:na]
	at org.sonar.server.platform.Platform.startLevel1Container(Platform.java:175) ~[sonar-server-5.6.3.jar:na]
	at org.sonar.server.platform.Platform.init(Platform.java:90) ~[sonar-server-5.6.3.jar:na]
	at org.sonar.server.platform.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:43) ~[sonar-server-5.6.3.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398) [tomcat-embed-core-8.0.32.jar:8.0.32]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.)
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044) ~[commons-dbcp-1.4.jar:1.4]
	at org.sonar.db.profiling.NullConnectionInterceptor.getConnection(NullConnectionInterceptor.java:31) ~[sonar-db-5.6.3.jar:na]
	at org.sonar.db.profiling.ProfiledDataSource.getConnection(ProfiledDataSource.java:323) ~[sonar-db-5.6.3.jar:na]
	at org.sonar.db.DefaultDatabase.checkConnection(DefaultDatabase.java:102) ~[sonar-db-5.6.3.jar:na]
	... 30 common frames omitted
Caused by: org.postgresql.util.PSQLException: Connection refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:215) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:64) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:144) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:29) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:21) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:31) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.Driver.makeConnection(Driver.java:410) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.Driver.connect(Driver.java:280) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545) ~[commons-dbcp-1.4.jar:1.4]
	... 35 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_111]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_111]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_111]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_111]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_111]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_111]
	at org.postgresql.core.PGStream.<init>(PGStream.java:61) ~[postgresql-9.3-1102-jdbc41.jar:na]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:109) ~[postgresql-9.3-1102-jdbc41.jar:na]
	... 47 common frames omitted
2016.12.04 14:14:26 ERROR web[o.a.c.c.StandardContext] One or more listeners failed to start. Full details will be found in the appropriate container log file
2016.12.04 14:14:26 ERROR web[o.a.c.c.StandardContext] Context [] startup failed due to previous errors
2016.12.04 14:14:26 WARN  web[o.a.c.l.WebappClassLoaderBase] The web application [ROOT] appears to have started a thread named [Timer-0] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)
 java.util.TimerThread.mainLoop(Timer.java:552)
 java.util.TimerThread.run(Timer.java:505)
2016.12.04 14:14:26 INFO  web[o.a.c.h.Http11NioProtocol] Starting ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.12.04 14:14:26 INFO  web[o.s.s.a.TomcatAccessLog] Web server is started
2016.12.04 14:14:26 INFO  web[o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2016.12.04 14:14:26 WARN  web[o.s.p.ProcessEntryPoint] Fail to start web
java.lang.IllegalStateException: Webapp did not start
	at org.sonar.server.app.EmbeddedTomcat.isUp(EmbeddedTomcat.java:84) ~[sonar-server-5.6.3.jar:na]
	at org.sonar.server.app.WebServer.isUp(WebServer.java:47) [sonar-server-5.6.3.jar:na]
	at org.sonar.process.ProcessEntryPoint.launch(ProcessEntryPoint.java:105) ~[sonar-process-5.6.3.jar:na]
	at org.sonar.server.app.WebServer.main(WebServer.java:68) [sonar-server-5.6.3.jar:na]
2016.12.04 14:14:26 INFO  web[o.a.c.h.Http11NioProtocol] Pausing ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.12.04 14:14:27 INFO  web[o.a.c.h.Http11NioProtocol] Stopping ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.12.04 14:14:28 INFO  web[o.a.c.h.Http11NioProtocol] Destroying ProtocolHandler ["http-nio-0.0.0.0-9000"]
2016.12.04 14:14:28 INFO  web[o.s.s.a.TomcatAccessLog] Web server is stopped
2016.12.04 14:14:28 INFO  app[o.s.p.m.Monitor] Process[es] is stopping
2016.12.04 14:14:28 INFO   es[o.s.p.StopWatcher]  Stopping process
2016.12.04 14:14:28 INFO   es[o.elasticsearch.node]  [sonar-1480860860022] stopping ...
2016.12.04 14:14:28 INFO   es[o.elasticsearch.node]  [sonar-1480860860022] stopped
2016.12.04 14:14:28 INFO   es[o.elasticsearch.node]  [sonar-1480860860022] closing ...
2016.12.04 14:14:28 INFO   es[o.elasticsearch.node]  [sonar-1480860860022] closed
2016.12.04 14:14:29 INFO  app[o.s.p.m.Monitor] Process[es] is stopped`
```

Is there something I'm doing wrong?

Thanks & Regards.

**Comment by Godin** [comment]
@blackfinn IMO message
```
Can not connect to database. Please check connectivity and settings
```
is pretty clear. You've specified that SonarQube should connect to PostgreSQL at localhost
```
SONARQUBE_JDBC_URL=jdbc:postgresql://localhost/sonar 
```
but SonarQube container itself (localhost) doesn't contain PostgreSQL.

**Comment by blackfinn** [comment]
Ah, thanks - honestly - that was my first assumption - but I'm not very familiar with java... - but btw. - what would be a good setup - the database within the container? Or somewhere else?

Thanks & Regards.

**Comment by Godin** [comment]
> what would be a good setup

depends on the needs, environment, etc
