### ISSUE TITLE
java.nio.file.NoSuchFileException: /opt/sonarqube/temp/README.txt

### ISSUE THREAD

**Issue by LazGit** [SonarSource/docker-sonarqube#62]
Hello,

I'm using sonarqube:alpine with docker. I always get an error during a restart :
```
2016.12.28 07:00:34 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
Exception in thread "main" java.lang.RuntimeException: Failed to reset file system
        at org.sonar.process.monitor.Monitor.resetFileSystem(Monitor.java:133)
        at org.sonar.process.monitor.Monitor.startProcesses(Monitor.java:113)
        at org.sonar.process.monitor.Monitor.start(Monitor.java:107)
        at org.sonar.application.App.start(App.java:73)
        at org.sonar.application.App.main(App.java:184)
Caused by: java.nio.file.NoSuchFileException: /opt/sonarqube/temp/README.txt
```
But the file '/opt/sonarqube/temp/README.txt' does not exist. Everything works fine if I create the file manually.
The problem occurs during a docker restart or sonarqube restart after installing plugins.

**Comment by kalidasya** [comment]
@LazGit you are a lifesaver, I could not figure out what is wrong with my docker container, creating the file is indeed a working workaround

**Comment by degree** [comment]
Actually nothing helps in my case. I tried creating file, deleting, moving directory, changing access rights, etc.... 

I just see 
```
root@ap-sonarqube-01:/opt/sonarqube# ls -al temp
ls: cannot access temp/README.txt: No such file or directory
total 4
drwxrwxrwx 1 root root   42 Mar  3 10:21 .
drwxr-xr-x 1 root root   39 Mar  3 10:17 ..
?????????? ? ?    ?       ?            ? README.txt
-rw-r--r-- 1 root root 2560 Mar  3 10:21 sharedmemory
```

after restart of sonarqube. This also affects :lts version.

**Comment by Asdafers** [comment]
+1 any news on a possible solution?

**Comment by xift810** [comment]
Mount temp folder, and you will solve it.
`sonarqube:
    image: sonarqube
    user: root
    ports:
     - "9000:9000"
     - "5432:5432"
    links:
      - db:db
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
     - /etc/pki:/etc/pki
     - /opt/mount1/sonarqube/data:/opt/sonarqube/data
     - /opt/mount1/sonarqube/conf:/opt/sonarqube/conf
     - /opt/mount1/sonarqube/extensions:/opt/sonarqube/extensions
     - /opt/mount1/sonarqube/tmp:/opt/sonarqube/temp`

**Comment by ogradyjd** [comment]
I just hit this today.  Running on Redhat 7.2, Docker version 17.05.0-ce, build 89658be, Sonar 6.4, running with a simple `docker run` command - nothing fancy.

@xift810 I'm not sure how to do what you've said - do you mean I have to modify the wrapper.conf in a Dockerfile that I write?

Devs: This makes it impossible to update Sonar when running in docker.  It's been around for 7 months now.  Anyone want to weigh in on this?

**Comment by Godin** [comment]
@ogradyjd This is an open-source project, and it’s maintained by volunteers. No need to say "it has been X months..." - pull-requests are welcomed from anyone who knows how to improve this.

**Comment by ogradyjd** [comment]
@Godin Fair enough.  I'm probably not the right person to be looking for linux-docker file system problems, but I'll give it a go.  So far, though, I've only found references that seem to indicate these are "ghost files" that have no inode number, or some such like that.   I think the below discussion is close, but since I'm new to docker, I'm not sure how the sonar-docker image is creating a bad or damaged container filesystem every time.

I'll look into it more, but I'm time-boxed on this.  If anyone has any more info or can contribute knowledge from the docker side of things, maybe we can triangulate on what the source of the problem is.   I'm guessing not everyone that uses this image has this problem?

https://unix.stackexchange.com/questions/148486/delete-ghost-files-with-special-characters

**Comment by Godin** [comment]
@ogradyjd and others - what are the **exact steps** to reproduce this?

I'm asking because can't reproduce:
```
$ docker --version
Docker version 17.06.0-ce, build 02c1d87

$ docker images
sonarqube           5.6.6-alpine        e9165a354539        2 weeks ago         248MB

$ docker run -d --name sonarqube -p 9000:9000 sonarqube:5.6.6-alpine

$ docker restart sonarqube

$ docker stop sonarqube

$ docker start sonarqube

$ docker logs sonarqube | grep -E "Web server is (stopped|started)"
2017.07.13 10:29:33 INFO  web[o.s.s.a.TomcatAccessLog] Web server is started
2017.07.13 10:31:14 INFO  web[o.s.s.a.TomcatAccessLog] Web server is stopped
2017.07.13 10:31:46 INFO  web[o.s.s.a.TomcatAccessLog] Web server is started
2017.07.13 10:32:12 INFO  web[o.s.s.a.TomcatAccessLog] Web server is stopped
2017.07.13 10:32:52 INFO  web[o.s.s.a.TomcatAccessLog] Web server is started
```

After such restarts there is no exceptions in log:
```
$ docker logs sonarqube | grep "Exception" | wc -l
0
```

**Comment by v-chyzhevskyi** [comment]
@Godin for reproducing this exception you need to use sonar of 6.* version, not 5.*
I reproduced this error on sonar 6.5.

**Comment by Godin** [comment]
@v-chyzhevskyi 

```
$ docker run -d --name sonarqube -p 9000:9000 sonarqube:6.5-alpine

$ docker restart sonarqube

$ docker stop sonarqube

$ docker start sonarqube

$ docker logs sonarqube  | grep -E "\[web\] is"
2017.09.09 10:23:01 INFO  app[][o.s.a.SchedulerImpl] Process[web] is up
2017.09.09 10:23:15 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2017.09.09 10:23:34 INFO  app[][o.s.a.SchedulerImpl] Process[web] is up
2017.09.09 10:23:57 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2017.09.09 10:24:28 INFO  app[][o.s.a.SchedulerImpl] Process[web] is up

$ docker logs sonarqube | grep "Exception" | wc -l 
0
```

**Comment by thienan93** [comment]
I have faced the same issue.

Sonar version: Version 6.5 (build 27846) 
```
$ docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
Here is errors:
```
2017.09.28 09:32:17 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
Exception in thread "main" java.nio.file.NoSuchFileException: /opt/sonarqube/temp/README.txt
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
        at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
        at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
        at java.nio.file.Files.walkFileTree(Files.java:2706)
        at org.sonar.application.AppFileSystem.createOrCleanTempDirectory(AppFileSystem.java:96)
        at org.sonar.application.AppFileSystem.reset(AppFileSystem.java:62)
        at org.sonar.application.App.start(App.java:53)
        at org.sonar.application.App.main(App.java:75)
````

**Comment by thienan93** [comment]
I use Sonar version 6.4 (build 25310) and do not face this issue.

**Comment by Godin** [comment]
@thienan93 

```
$ docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ docker images
sonarqube           6.5                 7b4cbfc2b51a        2 weeks ago         916MB

$ docker run -d --name sonarqube -p 9000:9000 sonarqube:6.5

$ docker restart sonarqube

$ docker stop sonarqube

$ docker start sonarqube

$ docker logs sonarqube  | grep -E "\[web\] is"
2017.09.28 10:15:22 INFO  app[][o.s.a.SchedulerImpl] Process[web] is up
2017.09.28 10:15:39 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2017.09.28 10:16:07 INFO  app[][o.s.a.SchedulerImpl] Process[web] is up
2017.09.28 10:16:32 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2017.09.28 10:17:03 INFO  app[][o.s.a.SchedulerImpl] Process[web] is up

$ docker logs sonarqube | grep "Exception" | wc -l 
0
```

**Comment by thienan93** [comment]
I used docker-compose and volumes:
```
version: '2'
services:
  sonarqube:
    restart: always
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgre:5432/sonar
    volumes:
      - /opt/sonarqube/conf:/opt/sonarqube/conf
      - /opt/sonarqube/data:/opt/sonarqube/data
      - /opt/sonarqube/extensions:/opt/sonarqube/extensions
      - /opt/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - /opt/sonarqube/temp:/opt/sonarqube/temp
    command: -Dhttps.proxyHost=192.168.1.100 -Dhttps.proxyPort=8080 -Dhttp.proxyHost=192.168.1.100 -Dhttp.proxyPort=8080
  postgre:
    restart: always
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /opt/sonarqube/postgresql:/var/lib/postgresql
      - /opt/sonarqube/postgresql/data:/var/lib/postgresql/data
networks:
  sonarnet:
    driver: bridge
```

**Comment by Godin** [comment]
@thienan93 `docker-compose`with volumes also works fine:
```
$ mkdir -p /tmp/sonarqube

$ cd /tmp/sonarqube

$ cat <<END > docker-compose.yml
version: '2'
services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    volumes:
      - /tmp/sonarqube/conf:/opt/sonarqube/conf
      - /tmp/sonarqube/data:/opt/sonarqube/data
      - /tmp/sonarqube/extensions:/opt/sonarqube/extensions
      - /tmp/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
      - /tmp/sonarqube/temp:/opt/sonarqube/temp
  postgres:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /tmp/sonarqube/postgresql:/var/lib/postgresql
      - /tmp/sonarqube/postgresql/data:/var/lib/postgresql/data
networks:
  sonarnet:
    driver: bridge
END

$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
postgres            latest              1227c4263c8c        10 days ago         265MB
sonarqube           latest              7b4cbfc2b51a        2 weeks ago         916MB

$ docker-compose create postgres

$ docker-compose start postgres

$ docker-compose create sonarqube

$ docker-compose start sonarqube

$ docker-compose restart sonarqube

$ $ docker logs sonarqube_sonarqube_1  | grep -E "\[web\] is"
2017.09.29 10:06:35 INFO  app[][o.s.a.SchedulerImpl] Process[web] is up
2017.09.29 10:07:14 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2017.09.29 10:07:33 INFO  app[][o.s.a.SchedulerImpl] Process[web] is up

$ docker logs sonarqube_sonarqube_1 | grep "Exception" | wc -l
0
```

And let's clarify following moment - statement that there is problem with image/`Dockerfile` for `6.5` and no such problem with `6.4` is extremely strange, because the only difference between them is https://github.com/SonarSource/docker-sonarqube/commit/c6aa0bbe967999f37cfa64522b3ae6ff0fda04de So either there is problem with both, or with none of them, or problem is not at all in `Dockerfile`. And in the last case there is nothing to fix in images/`Dockerfile`s provided by this repository. And this repository/issue-tracker is not the right place to get generic support about proper usage of `docker`, `docker-compose`, volumes, your infrastructure around them, etc etc. Thank you for your understanding.

**Comment by thienan93** [comment]
@Godin,
I do not go to here to ask about usage of docker or docker-compose. I just want to report an issue that I've faced and try to give more related information.

**Comment by maodia** [comment]
docker installed  in centos 7 linux   on a vmware wrokstation 14 player ,  

`[root@master ~]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-88.git07f3374.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      07f3374/1.13.1
 Built:           Fri Dec  7 16:13:51 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-88.git07f3374.el7.centos.x86_64
 Go version:      go1.9.4
 Git commit:      07f3374/1.13.1
 Built:           Fri Dec  7 16:13:51 2018
 OS/Arch:         linux/amd64
 Experimental:    false`

steps:
1.install the sonarqube:
docker run --name db -e POSTGRES_USER=sonar -e POSTGRES_PASSWORD=sonar -d postgres
docker run -d --name sq  --link db -e SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar  -p 9000:9000 sonarqube

the current sonarqube image is v7.5

2.login with admin,go to administrator - marketplace,uninstall the plugin "SonarFlex",the docker logs:

2019.01.11 08:56:41 INFO  web[AWg8HR2k1sF53lwNAAAZ][o.s.s.p.ServerPluginRepository] Uninstalling plugin SonarFlex [flex]
2019.01.11 08:57:02 ERROR web[AWg8HR2k1sF53lwNAAAa][o.s.s.p.UpdateCenterClient] Fail to connect to update center
org.sonar.api.utils.SonarException: Fail to download: https://update.sonarsource.org/update-center.properties (no proxy)
        at org.sonar.core.util.DefaultHttpDownloader.failToDownload(DefaultHttpDownloader.java:155)
        at org.sonar.core.util.DefaultHttpDownloader.readString(DefaultHttpDownloader.java:113)
        at org.sonar.api.utils.UriReader.readString(UriReader.java:70)
        at org.sonar.server.plugins.UpdateCenterClient.init(UpdateCenterClient.java:99)
        at org.sonar.server.plugins.UpdateCenterClient.getUpdateCenter(UpdateCenterClient.java:82)
        at org.sonar.server.plugins.UpdateCenterMatrixFactory.getUpdateCenter(UpdateCenterMatrixFactory.java:44)
        at org.sonar.server.plugins.ws.PluginWSCommons.compatiblePlugins(PluginWSCommons.java:244)
        at org.sonar.server.plugins.ws.PluginWSCommons.compatiblePluginsByKey(PluginWSCommons.java:249)
        at org.sonar.server.plugins.ws.PendingAction.handle(PendingAction.java:88)
        at org.sonar.server.ws.WebServiceEngine.execute(WebServiceEngine.java:110)
        at org.sonar.server.ws.WebServiceFilter.doFilter(WebServiceFilter.java:88)
        at org.sonar.server.platform.web.MasterServletFilter$GodFilterChain.doFilter(MasterServletFilter.java:126)
        at org.sonar.server.platform.web.MasterServletFilter.doFilter(MasterServletFilter.java:95)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:87)
        at org.sonar.server.user.UserSessionFilter.doFilter(UserSessionFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.CacheControlFilter.doFilter(CacheControlFilter.java:76)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.SecurityServletFilter.doHttpFilter(SecurityServletFilter.java:76)
        at org.sonar.server.platform.web.SecurityServletFilter.doFilter(SecurityServletFilter.java:48)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.RedirectFilter.doFilter(RedirectFilter.java:61)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.requestid.RequestIdFilter.doFilter(RequestIdFilter.java:63)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.sonar.server.platform.web.RootFilter.doFilter(RootFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.filters.SetCharacterEncodingFilter.doFilter(SetCharacterEncodingFilter.java:108)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
        at org.sonar.core.util.DefaultHttpDownloader$BaseHttpDownloader$HttpInputSupplier.getInput(DefaultHttpDownloader.java:272)
        at org.sonar.core.util.DefaultHttpDownloader.readString(DefaultHttpDownloader.java:111)
        ... 52 common frames omitted

3.click restart button when promoted,and the docker logs:
2019.01.11 08:59:16 INFO  ce[][o.s.p.StopWatcher] Stopping process
2019.01.11 08:59:16 INFO  ce[][o.s.ce.app.CeServer] Compute Engine is stopping...
2019.01.11 08:59:16 INFO  ce[][o.s.c.t.CeProcessingSchedulerImpl] Waiting for workers to finish in-progress tasks
2019.01.11 08:59:18 INFO  ce[][o.s.ce.app.CeServer] Compute Engine is stopped
2019.01.11 08:59:19 INFO  app[][o.s.a.SchedulerImpl] Process [ce] is stopped
2019.01.11 08:59:19 INFO  web[][o.s.p.StopWatcher] Stopping process
2019.01.11 08:59:23 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2019.01.11 08:59:23 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
2019.01.11 08:59:23 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2019.01.11 08:59:23 INFO  app[][o.s.a.SchedulerImpl] SonarQube is restarting
2019.01.11 08:59:23 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
2019.01.11 08:59:23 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2019.01.11 08:59:23 ERROR app[][o.s.a.SchedulerImpl] Fail to restart
java.nio.file.NoSuchFileException: /opt/sonarqube/temp/README.txt
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
        at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.nio.file.Files.readAttributes(Files.java:1737)
        at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:225)
        at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
        at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
        at java.nio.file.Files.walkFileTree(Files.java:2706)
        at org.sonar.application.AppFileSystem.createOrCleanTempDirectory(AppFileSystem.java:96)
        at org.sonar.application.AppFileSystem.reset(AppFileSystem.java:62)
        at org.sonar.application.AppReloaderImpl.reload(AppReloaderImpl.java:60)
        at org.sonar.application.SchedulerImpl$RestarterThread.run(SchedulerImpl.java:295)


so you can not start the docker instance again.

**Comment by ginsburgnm** [comment]
@Godin 
This is actually an issue with security context, and still present today. I ran into this with the latest release. 

Here's what's happening. When you run the docker image locally, it doesn't really matter; you can have a `USER sonarqube` run things. However, when you are in an enterprise environment, what is likely the case is that your kubernetes/openshift/whatever environment will not allow you to specify a user to run as; this is a security policy. If the policy on the kube cluster is set to allow `anyuid` and individual "forgets" to set `USER` in their `Dockerfile` then that individual is root in the container. And bad things happen when you run a container as root.

When you can't set `USER` the kube cluster just gives you a misc user, this user does not have access to files owned by `sonarqube`

But let's keep going, why do you need `USER sonarqube`? well, taking it out, I saw that elasticsearch is embedded in there, and you can't run that as root; well great. likely that means additional work needs to be done to appropriately containerize this application, but let's skip that.

How would one run this application in an (appropriately) locked down kube cluster?

```
# Slightly modified your Dockerfil
FROM openjdk:11-jre-slim

RUN apt-get update \
    && apt-get install -y curl gnupg2 unzip \
    && rm -rf /var/lib/apt/lists/*

ENV SONAR_VERSION=7.9.2 \
    SONARQUBE_HOME=/opt/sonarqube \
    SONARQUBE_JDBC_USERNAME=sonar \
    SONARQUBE_JDBC_PASSWORD=sonar \
    SONARQUBE_JDBC_URL=""

# Http port
EXPOSE 9000

RUN for server in $(shuf -e ha.pool.sks-keyservers.net \
                            hkp://p80.pool.sks-keyservers.net:80 \
                            keyserver.ubuntu.com \
                            hkp://keyserver.ubuntu.com:80 \
                            pgp.mit.edu) ; do \
        gpg --batch --keyserver "$server" --recv-keys F1182E81C792928921DBCAB4CFCA4A29D26468DE && break || : ; \
    done

RUN set -x \
    && cd /opt \
    && curl -o sonarqube.zip -fSL https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-$SONAR_VERSION.zip \
    && curl -o sonarqube.zip.asc -fSL https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-$SONAR_VERSION.zip.asc \
    && gpg --batch --verify sonarqube.zip.asc sonarqube.zip \
    && unzip -q sonarqube.zip \
    && mv sonarqube-$SONAR_VERSION sonarqube \
    && rm sonarqube.zip* \
    && rm -rf $SONARQUBE_HOME/bin/* \
    && touch $SONARQUBE_HOME/logs/es.log

COPY run.sh $SONARQUBE_HOME/bin/

# well, since we can't choose which user we are to run as
# let's allow literally anyone to read/write/execute anything in /opt/sonarqube
# this is disgusting, and also increases build times by a lot
RUN chmod -R 777 "$SONARQUBE_HOME" 

VOLUME "$SONARQUBE_HOME/data"

WORKDIR $SONARQUBE_HOME
# elasticsearch will still gripe if you don't specify a user when you're testing locally 
# so you need this for the environment's that will let you run as root
RUN groupadd -r sonarqube && useradd -r -g sonarqube sonarqube
USER sonarqube
ENTRYPOINT ["/opt/sonarqube/bin/run.sh"]
```

The reason I'm not opening a PR here, is because this is still a bad solution. It does work in more cases than your current Dockerfile, but the fact that I have to do this suggests there is a greater issue at hand and this is just a disgusting workaround; merging this in will likely make people ignore the actual issue.

Hopefully someone finds this helpful.
