### ISSUE TITLE
Deleting Failed Jobs

### ISSUE THREAD

**Issue by montge** [SonarSource/docker-sonarqube#80]
We're having some issue deleting a failed job from sonarqube.  This is associated with a issue that we ran out of a memory.  Then it appeared to work, but ran out again later on.  We deleted it through the GUI, but now it seems to have something in the DB that is causing a crash on startup.  Any recommendations, or is it easier to 'start over'?

```
sonarqube_1  | 2017.05.01 20:51:20 ERROR ce[AVuVcwNtLdf8QcRv8YoL][o.s.s.c.t.s.ComputationStepExecutor] Execution of listener failed
sonarqube_1  | java.lang.NullPointerException: key can not be null
sonarqube_1  | 	at java.util.Objects.requireNonNull(Objects.java:228)
sonarqube_1  | 	at org.sonar.server.computation.task.projectanalysis.api.posttask.ProjectImpl.<init>(ProjectImpl.java:35)
sonarqube_1  | 	at org.sonar.server.computation.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.createProject(PostProjectAnalysisTasksExecutor.java:127)
sonarqube_1  | 	at org.sonar.server.computation.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.createProjectAnalysis(PostProjectAnalysisTasksExecutor.java:116)
sonarqube_1  | 	at org.sonar.server.computation.task.projectanalysis.api.posttask.PostProjectAnalysisTasksExecutor.finished(PostProjectAnalysisTasksExecutor.java:98)
sonarqube_1  | 	at org.sonar.server.computation.task.step.ComputationStepExecutor.executeListener(ComputationStepExecutor.java:71)
sonarqube_1  | 	at org.sonar.server.computation.task.step.ComputationStepExecutor.execute(ComputationStepExecutor.java:56)
sonarqube_1  | 	at org.sonar.server.computation.task.projectanalysis.taskprocessor.ReportTaskProcessor.process(ReportTaskProcessor.java:75)
sonarqube_1  | 	at org.sonar.server.computation.taskprocessor.CeWorkerCallableImpl.executeTask(CeWorkerCallableImpl.java:85)
sonarqube_1  | 	at org.sonar.server.computation.taskprocessor.CeWorkerCallableImpl.call(CeWorkerCallableImpl.java:58)
sonarqube_1  | 	at org.sonar.server.computation.taskprocessor.CeWorkerCallableImpl.call(CeWorkerCallableImpl.java:36)
sonarqube_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
sonarqube_1  | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
sonarqube_1  | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
sonarqube_1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
sonarqube_1  | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
sonarqube_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
sonarqube_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
sonarqube_1  | 	at java.lang.Thread.run(Thread.java:745)
sonarqube_1  | 2017.05.01 20:51:21 ERROR ce[AVuVcwNtLdf8QcRv8YoL][o.s.s.c.t.CeWorkerCallableImpl] Failed to execute task AVuVcwNtLdf8QcRv8YoL
sonarqube_1  | org.sonar.api.utils.MessageException: Compute Engine task component key is null. Project with UUID AVuVcvYCLdf8QcRv8YoK must have been deleted since report was uploaded. Can not proceed.
sonarqube_1  | 2017.05.01 20:51:26 ERROR ce[AVuVcwNtLdf8QcRv8YoL][o.s.s.c.t.CeWorkerCallableImpl] Executed task | type=REPORT | id=AVuVcwNtLdf8QcRv8YoL | time=22708ms
```

**Comment by Godin** [comment]
This is an issue tracker of a Docker image. For the general questions about SonarQube please follow https://www.sonarqube.org/community/feedback/
