### ISSUE TITLE
Problems with default H2 connection

### ISSUE THREAD

**Issue by IrishkA13** [SonarSource/docker-sonarqube#97]
Hi!
My sonarqube container is down very often because of broken connection to default H2-database. 
Default database is ok for my use so I don't need additional db configuration. 
After some time the container is down. Start container again recover it for some time but then it is down again.
Here is the logs of container.

```
org.apache.ibatis.exceptions.PersistenceException:
### Error querying database.  Cause: org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused (Connection refused): 127.0.0.1:9092" [90067-176]
### The error may exist in org.sonar.db.ce.CeQueueMapper
### The error may involve org.sonar.db.ce.CeQueueMapper.selectPendingByMinimumExecutionCount
### The error occurred while executing a query
### Cause: org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused (Connection refused): 127.0.0.1:9092" [90067-176]
        at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:26)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:111)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:102)
        at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:119)
        at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:63)
        at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
        at com.sun.proxy.$Proxy27.selectPendingByMinimumExecutionCount(Unknown Source)
        at org.sonar.db.ce.CeQueueDao.selectPendingByMinimumExecutionCount(CeQueueDao.java:87)
        at org.sonar.ce.queue.InternalCeQueueImpl.cancelWornOuts(InternalCeQueueImpl.java:163)
        at org.sonar.ce.cleaning.CeCleaningSchedulerImpl.cancelWornOuts(CeCleaningSchedulerImpl.java:73)
        at org.sonar.ce.cleaning.CeCleaningSchedulerImpl.cleanCeQueue(CeCleaningSchedulerImpl.java:62)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: Connection is broken: "java.net.ConnectException: Connection refused (Connection refused): 127.0.0.1:9092" [90067-176]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
        at org.h2.message.DbException.get(DbException.java:167)
        at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:434)
        at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:311)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:107)
        at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:91)
        at org.h2.Driver.connect(Driver.java:74)
        at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
        at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
        at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1148)
        at org.apache.commons.dbcp.PoolingDataSource.getConnection(PoolingDataSource.java:106)
        at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
        at org.sonar.db.profiling.NullConnectionInterceptor.getConnection(NullConnectionInterceptor.java:31)
        at org.sonar.db.profiling.ProfiledDataSource.getConnection(ProfiledDataSource.java:323)
        at org.apache.ibatis.transaction.jdbc.JdbcTransaction.openConnection(JdbcTransaction.java:134)
        at org.apache.ibatis.transaction.jdbc.JdbcTransaction.getConnection(JdbcTransaction.java:61)
        at org.apache.ibatis.executor.BaseExecutor.getConnection(BaseExecutor.java:279)
        at org.apache.ibatis.executor.ReuseExecutor.prepareStatement(ReuseExecutor.java:75)
        at org.apache.ibatis.executor.ReuseExecutor.doQuery(ReuseExecutor.java:56)
        at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:267)
        at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:137)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:96)
        at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:77)
        at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:108)
        ... 16 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at org.h2.util.NetUtils.createSocket(NetUtils.java:123)
        at org.h2.util.NetUtils.createSocket(NetUtils.java:103)
        at org.h2.engine.SessionRemote.initTransfer(SessionRemote.java:100)
        at org.h2.engine.SessionRemote.connectServer(SessionRemote.java:430)
        ... 37 common frames omitted
```

My docker-compose.yml:
```
  sonarqube:
    image: sonarqube
    command: -Dsonar.web.context=/sonarqube
    ports:
    - "9000:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    container_name: "***-sonarqube"
```

**Comment by Godin** [comment]
Can't reproduce using

```
$ docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.8.3
 Git commit:   c6d412e
 Built:        Fri Jul 14 17:56:32 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   c6d412e
 Built:        Fri Jul 14 17:56:32 2017
 OS/Arch:      linux/amd64
 Experimental: false

$ docker-compose version
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.4.2
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017

$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
sonarqube           6.4                 7bbef44cb183        15 hours ago        890 MB
```

and `docker-compose.yml`:

```
version: "2"

services:
  sonarqube:
    image: sonarqube:6.4
    command: -Dsonar.web.context=/sonarqube
    ports:
      - "9000:9000"
```

If you're using Azure, EC2 or similar container services, then maybe this exception is a consequence of the fact that infrastructure decides to stop container - please check with service provider.

There is no precedents of such exception outside of Docker and there is no magic in this Docker image - just a Java and bunch of SonarQube JAR files running as a Java application, so there is very high chances that your issue is related to your infrastructure.

Last but not least - as stated in SonarQube UI: "Embedded database should be used for evaluation purpose only", i.e. it is suitable only for short demos, but not for production use and especially for a long-running server instance. So don't be surprised about scalability and reliability issues - you have been warned.
